import type { Locale } from "@/i18n/locales";
import type { RoundCoreState } from "@/lib/roundExperience";

type LifecycleStage = { title: string; body: string };
type ProofStage = { title: string; body: string };

export type CeremonyContent = {
  core: {
    eyebrow: string;
    title: string;
    status: Record<RoundCoreState, string>;
    message: Record<RoundCoreState, string>;
    round: string;
    pool: string;
    target: string;
    tickets: string;
    price: string;
    verifiedSource: string;
  };
  lifecycle: {
    eyebrow: string;
    title: string;
    intro: string;
    current: string;
    completed: string;
    future: string;
    stages: readonly LifecycleStage[];
  };
  participation: {
    share: string;
    shareUnavailable: string;
    currentRound: string;
  };
  reveal: {
    eyebrow: string;
    title: string;
    intro: string;
    skip: string;
    complete: string;
    claim: string;
    verify: string;
  };
  proof: {
    eyebrow: string;
    title: string;
    intro: string;
    available: string;
    awaiting: string;
    event: string;
    stages: readonly ProofStage[];
  };
  security: {
    eyebrow: string;
    title: string;
    intro: string;
    network: string;
    contract: string;
    source: string;
    sourceValue: string;
    vrf: string;
    audit: string;
    auditValue: string;
    admin: string;
    adminValue: string;
    target: string;
    fixedTickets: string;
    oneRequest: string;
    seedWarning: string;
    transferWarning: string;
  };
};

const statusKeys: Record<RoundCoreState, string> = {
  disconnected: "Wallet disconnected",
  connecting: "Connecting wallet",
  wrongNetwork: "Wrong network",
  loading: "Reading Polygon",
  rpcError: "RPC unavailable",
  none: "Awaiting a new round",
  open: "Ticket sales open",
  randomnessRequested: "Waiting for Chainlink VRF",
  randomnessReady: "Randomness received",
  finalized: "Round finalized",
};

export const ceremonyContent: Record<Locale, CeremonyContent> = {
  en: {
    core: { eyebrow: "Live on-chain ceremony", title: "Seren Round Core", status: statusKeys, message: { disconnected: "Connect a wallet to synchronize the core with Polygon Mainnet.", connecting: "Establishing a private connection to your wallet.", wrongNetwork: "Switch to Polygon Mainnet to read the live round.", loading: "Reading the verified contract without fallback values.", rpcError: "The wallet RPC could not return the current round.", none: "The lotus rests until the contract opens a new round.", open: "The core gathers energy as confirmed tickets enter the round.", randomnessRequested: "Sales are closed. The ticket set is fixed while Chainlink responds.", randomnessReady: "Verifiable randomness is accepted; finalization is the next on-chain step.", finalized: "Ten winning ticket IDs are permanently available from the contract." }, round: "Round", pool: "Current pool", target: "Target", tickets: "Tickets", price: "Ticket price", verifiedSource: "Synchronized through your wallet · Polygon Mainnet" },
    lifecycle: { eyebrow: "Contract state map", title: "Round lifecycle", intro: "A stage advances only after its corresponding on-chain state is confirmed.", current: "Current", completed: "Completed", future: "Upcoming", stages: [{ title: "Sales", body: "The OPEN state allows contract-quoted ticket purchases." }, { title: "Closing", body: "An authorized administrator closes sales by starting the draw process." }, { title: "Chainlink VRF", body: "The fixed ticket set waits for one verifiable randomness request." }, { title: "Finalization", body: "Accepted randomness is converted into ten ordered winning ticket IDs." }, { title: "Prize claims", body: "Winners claim available prizes from the wallet that owns each ticket." }] },
    participation: { share: "Your tickets represent {percent}% of all tickets in this round.", shareUnavailable: "A ticket share is shown only after both counts are read from the contract.", currentRound: "Current round" },
    reveal: { eyebrow: "Confirmed on Polygon", title: "The round has been revealed", intro: "These positions preserve the contract order. Ticket IDs, owners and prizes are not shuffled by the interface.", skip: "Show all results", complete: "All ten on-chain positions are visible", claim: "Claim available prize", verify: "Verify address" },
    proof: { eyebrow: "Proof Explorer", title: "Verify the round, step by step", intro: "You do not need to trust project claims — every available stage can be checked independently.", available: "Confirmed evidence", awaiting: "Not yet confirmed", event: "Contract event", stages: [{ title: "Ticket purchase", body: "A confirmed buyTickets transaction created ticket ownership." }, { title: "Sales closed", body: "The VRF request transaction fixed the set of eligible tickets." }, { title: "Chainlink request", body: "The contract emitted a verifiable randomness request ID." }, { title: "Chainlink callback", body: "The coordinator callback was accepted by the lottery contract." }, { title: "Finalization", body: "The round was finalized in a confirmed transaction." }, { title: "Winning ticket IDs", body: "WinnerSelected events preserve the ordered ticket IDs." }, { title: "Prize allocation", body: "Finalized results expose the exact prize assigned to each position." }, { title: "Claim", body: "PrizeClaimed events prove self-service payout by winners." }] },
    security: { eyebrow: "Security Center", title: "Know exactly what you are interacting with", intro: "Published, verifiable facts — not a claim that the contract is risk-free.", network: "Network", contract: "Primary contract", source: "Source status", sourceValue: "Source code published and verified", vrf: "Randomness", audit: "External audit", auditValue: "No independent audit is claimed", admin: "Admin model", adminValue: "Authorized admins start the draw; the contract enforces its state transitions.", target: "The target pool is informational and does not trigger a draw.", fixedTickets: "After requestDraw, ticket sales are closed and the ticket set is fixed.", oneRequest: "The round snapshot records one accepted VRF request for the draw.", seedWarning: "Seren never asks for a seed phrase or private key.", transferWarning: "A direct POL transfer to the contract does not replace buying through the designated function." },
  },
  ru: {
    core: { eyebrow: "Живая on-chain церемония", title: "Ядро раунда Seren", status: { disconnected: "Кошелёк не подключён", connecting: "Подключение кошелька", wrongNetwork: "Неверная сеть", loading: "Чтение Polygon", rpcError: "RPC недоступен", none: "Ожидание нового раунда", open: "Продажи билетов открыты", randomnessRequested: "Ожидание Chainlink VRF", randomnessReady: "Случайность получена", finalized: "Раунд финализирован" }, message: { disconnected: "Подключите кошелёк, чтобы синхронизировать ядро с Polygon Mainnet.", connecting: "Устанавливается приватное соединение с вашим кошельком.", wrongNetwork: "Переключитесь на Polygon Mainnet для чтения живого раунда.", loading: "Читаем верифицированный контракт без подставных значений.", rpcError: "RPC кошелька не смог вернуть состояние текущего раунда.", none: "Лотос остаётся спокойным, пока контракт не откроет новый раунд.", open: "Ядро накапливает энергию по мере подтверждения новых билетов.", randomnessRequested: "Продажи закрыты. Состав билетов зафиксирован, ожидается Chainlink.", randomnessReady: "Проверяемая случайность принята; следующий on-chain этап — финализация.", finalized: "Десять выигрышных ticket ID навсегда доступны в контракте." }, round: "Раунд", pool: "Текущий фонд", target: "Целевой фонд", tickets: "Билеты", price: "Цена билета", verifiedSource: "Синхронизация через ваш кошелёк · Polygon Mainnet" },
    lifecycle: { eyebrow: "Карта состояния контракта", title: "Жизненный цикл раунда", intro: "Этап меняется только после подтверждения соответствующего on-chain состояния.", current: "Текущий", completed: "Завершён", future: "Предстоит", stages: [{ title: "Продажи", body: "В состоянии OPEN доступны покупки по точному quote контракта." }, { title: "Закрытие", body: "Уполномоченный администратор закрывает продажи, запуская процедуру розыгрыша." }, { title: "Chainlink VRF", body: "Зафиксированный состав билетов ожидает один запрос проверяемой случайности." }, { title: "Финализация", body: "Принятая случайность преобразуется в десять упорядоченных ticket ID." }, { title: "Получение призов", body: "Победители самостоятельно получают призы с кошелька-владельца билета." }] },
    participation: { share: "Ваши билеты составляют {percent}% от общего числа билетов текущего раунда.", shareUnavailable: "Доля показывается только после чтения обоих значений из контракта.", currentRound: "Текущий раунд" },
    reveal: { eyebrow: "Подтверждено в Polygon", title: "Результаты раунда раскрыты", intro: "Порядок полностью соответствует контракту. Интерфейс не перемешивает ticket ID, владельцев и призы.", skip: "Показать все результаты", complete: "Все десять on-chain позиций доступны", claim: "Получить доступный приз", verify: "Проверить адрес" },
    proof: { eyebrow: "Проверка раунда", title: "Проверьте каждый этап самостоятельно", intro: "Вам не нужно доверять заявлениям проекта — каждый доступный этап можно проверить самостоятельно.", available: "Подтверждённое доказательство", awaiting: "Ещё не подтверждено", event: "Событие контракта", stages: [{ title: "Покупка билета", body: "Подтверждённая транзакция buyTickets создала владение билетами." }, { title: "Закрытие продаж", body: "Транзакция запроса VRF зафиксировала состав участвующих билетов." }, { title: "Запрос Chainlink", body: "Контракт опубликовал ID запроса проверяемой случайности." }, { title: "Callback Chainlink", body: "Callback координатора был принят контрактом лотереи." }, { title: "Финализация", body: "Раунд финализирован подтверждённой транзакцией." }, { title: "Winning ticket ID", body: "События WinnerSelected сохраняют порядок выигрышных билетов." }, { title: "Начисление призов", body: "Финальные результаты раскрывают точную сумму для каждой позиции." }, { title: "Claim", body: "События PrizeClaimed подтверждают самостоятельную выплату победителям." }] },
    security: { eyebrow: "Центр безопасности", title: "Понимайте, с чем взаимодействует кошелёк", intro: "Опубликованные и проверяемые факты — без заявления о полной безопасности контракта.", network: "Сеть", contract: "Основной контракт", source: "Статус исходного кода", sourceValue: "Исходный код опубликован и верифицирован", vrf: "Случайность", audit: "Внешний аудит", auditValue: "Независимый аудит не заявлен", admin: "Административная модель", adminValue: "Уполномоченные администраторы запускают розыгрыш; переходы состояний контролирует контракт.", target: "Целевой фонд является ориентиром и не запускает розыгрыш.", fixedTickets: "После requestDraw продажи закрываются, а состав билетов фиксируется.", oneRequest: "Снимок раунда хранит один принятый VRF request для розыгрыша.", seedWarning: "Seren никогда не запрашивает seed-фразу или private key.", transferWarning: "Обычный перевод POL на адрес контракта не заменяет покупку билета через предусмотренную функцию." },
  },
  es: {
    core: { eyebrow: "Ceremonia on-chain en vivo", title: "Núcleo de ronda Seren", status: { disconnected: "Cartera desconectada", connecting: "Conectando cartera", wrongNetwork: "Red incorrecta", loading: "Leyendo Polygon", rpcError: "RPC no disponible", none: "Esperando nueva ronda", open: "Venta de boletos abierta", randomnessRequested: "Esperando Chainlink VRF", randomnessReady: "Aleatoriedad recibida", finalized: "Ronda finalizada" }, message: { disconnected: "Conecta una cartera para sincronizar el núcleo con Polygon Mainnet.", connecting: "Estableciendo una conexión privada con tu cartera.", wrongNetwork: "Cambia a Polygon Mainnet para leer la ronda.", loading: "Leyendo el contrato verificado sin valores alternativos.", rpcError: "El RPC de la cartera no devolvió la ronda actual.", none: "El loto descansa hasta que el contrato abra una nueva ronda.", open: "El núcleo acumula energía con cada boleto confirmado.", randomnessRequested: "Ventas cerradas. El conjunto de boletos está fijado mientras responde Chainlink.", randomnessReady: "Aleatoriedad verificable aceptada; falta la finalización.", finalized: "Los diez ID ganadores están disponibles permanentemente en el contrato." }, round: "Ronda", pool: "Fondo actual", target: "Objetivo", tickets: "Boletos", price: "Precio", verifiedSource: "Sincronizado por tu cartera · Polygon Mainnet" },
    lifecycle: { eyebrow: "Mapa del contrato", title: "Ciclo de la ronda", intro: "Cada etapa avanza solo con confirmación on-chain.", current: "Actual", completed: "Completada", future: "Próxima", stages: [{ title: "Ventas", body: "OPEN permite compras con la cotización exacta del contrato." }, { title: "Cierre", body: "Un administrador autorizado inicia el proceso de sorteo." }, { title: "Chainlink VRF", body: "Los boletos fijados esperan una solicitud de aleatoriedad verificable." }, { title: "Finalización", body: "La aleatoriedad aceptada produce diez ID ganadores ordenados." }, { title: "Cobro", body: "Los ganadores cobran desde la cartera propietaria del boleto." }] },
    participation: { share: "Tus boletos representan el {percent}% del total de esta ronda.", shareUnavailable: "La proporción aparece solo tras leer ambos valores del contrato.", currentRound: "Ronda actual" },
    reveal: { eyebrow: "Confirmado en Polygon", title: "La ronda ha sido revelada", intro: "La interfaz conserva el orden del contrato sin mezclar resultados.", skip: "Mostrar todos", complete: "Las diez posiciones on-chain están visibles", claim: "Cobrar premio disponible", verify: "Verificar dirección" },
    proof: { eyebrow: "Explorador de pruebas", title: "Verifica cada etapa", intro: "No necesitas confiar en afirmaciones: comprueba cada etapa disponible.", available: "Prueba confirmada", awaiting: "Aún no confirmada", event: "Evento del contrato", stages: [{ title: "Compra", body: "Una transacción buyTickets confirmó la propiedad." }, { title: "Cierre", body: "La solicitud VRF fijó los boletos elegibles." }, { title: "Solicitud Chainlink", body: "El contrato emitió el ID de solicitud." }, { title: "Callback Chainlink", body: "El contrato aceptó el callback." }, { title: "Finalización", body: "La ronda fue finalizada on-chain." }, { title: "Boletos ganadores", body: "WinnerSelected conserva los ID ordenados." }, { title: "Asignación", body: "Los resultados exponen cada premio exacto." }, { title: "Cobro", body: "PrizeClaimed prueba el pago autónomo." }] },
    security: { eyebrow: "Centro de seguridad", title: "Comprende cada interacción", intro: "Hechos verificables, no una promesa de ausencia de riesgo.", network: "Red", contract: "Contrato principal", source: "Código", sourceValue: "Código publicado y verificado", vrf: "Aleatoriedad", audit: "Auditoría externa", auditValue: "No se afirma una auditoría independiente", admin: "Modelo admin", adminValue: "Admins autorizados inician el sorteo; el contrato aplica los estados.", target: "El fondo objetivo no inicia automáticamente el sorteo.", fixedTickets: "Tras requestDraw se cierran ventas y se fija el conjunto.", oneRequest: "La ronda registra una solicitud VRF aceptada.", seedWarning: "Seren nunca solicita frase semilla ni clave privada.", transferWarning: "Enviar POL directamente no sustituye la compra mediante la función prevista." },
  },
  zh: {
    core: { eyebrow: "实时链上仪式", title: "Seren 轮次核心", status: { disconnected: "钱包未连接", connecting: "正在连接钱包", wrongNetwork: "网络错误", loading: "正在读取 Polygon", rpcError: "RPC 不可用", none: "等待新轮次", open: "售票开放", randomnessRequested: "等待 Chainlink VRF", randomnessReady: "随机数已收到", finalized: "轮次已最终确认" }, message: { disconnected: "连接钱包以同步 Polygon 主网上的核心。", connecting: "正在与钱包建立私密连接。", wrongNetwork: "切换至 Polygon 主网以读取实时轮次。", loading: "正在读取已验证合约，不使用备用数值。", rpcError: "钱包 RPC 未能返回当前轮次。", none: "合约开启新轮次前，莲花保持平静。", open: "每张已确认票都会让核心积聚能量。", randomnessRequested: "售票已关闭，票集已固定，正在等待 Chainlink。", randomnessReady: "可验证随机数已接受，下一步为最终确认。", finalized: "十个中奖票号已永久记录在合约中。" }, round: "轮次", pool: "当前奖池", target: "目标", tickets: "票数", price: "票价", verifiedSource: "通过钱包同步 · Polygon 主网" },
    lifecycle: { eyebrow: "合约状态图", title: "轮次生命周期", intro: "只有链上状态确认后阶段才会推进。", current: "当前", completed: "已完成", future: "待进行", stages: [{ title: "售票", body: "OPEN 状态允许按合约精确报价购票。" }, { title: "关闭", body: "授权管理员启动开奖流程并关闭销售。" }, { title: "Chainlink VRF", body: "固定票集等待一次可验证随机数请求。" }, { title: "最终确认", body: "已接受随机数生成十个有序中奖票号。" }, { title: "领取奖金", body: "中奖者使用持票钱包自行领取。" }] },
    participation: { share: "你的票占本轮总票数的 {percent}%。", shareUnavailable: "仅在读取两个合约数值后显示占比。", currentRound: "当前轮次" },
    reveal: { eyebrow: "Polygon 已确认", title: "轮次结果已揭晓", intro: "界面保持合约顺序，不重排票号、地址或奖金。", skip: "显示全部结果", complete: "十个链上位置全部可见", claim: "领取可用奖金", verify: "验证地址" },
    proof: { eyebrow: "证明浏览器", title: "逐步验证轮次", intro: "无需相信项目声明，每个可用阶段都能独立验证。", available: "已确认凭证", awaiting: "尚未确认", event: "合约事件", stages: [{ title: "购票", body: "已确认 buyTickets 交易创建持票权。" }, { title: "关闭销售", body: "VRF 请求固定符合资格的票集。" }, { title: "Chainlink 请求", body: "合约发出随机数请求 ID。" }, { title: "Chainlink 回调", body: "彩票合约接受协调器回调。" }, { title: "最终确认", body: "轮次由已确认交易完成。" }, { title: "中奖票号", body: "WinnerSelected 保存有序票号。" }, { title: "奖金分配", body: "最终结果公开每个准确奖金。" }, { title: "领取", body: "PrizeClaimed 证明自主领取。" }] },
    security: { eyebrow: "安全中心", title: "了解钱包交互对象", intro: "展示可验证事实，而非无风险承诺。", network: "网络", contract: "主合约", source: "源码状态", sourceValue: "源码已发布并验证", vrf: "随机性", audit: "外部审计", auditValue: "不声明已完成独立审计", admin: "管理模型", adminValue: "授权管理员启动开奖，合约强制执行状态转换。", target: "目标奖池仅供参考，不会自动开奖。", fixedTickets: "requestDraw 后关闭售票并固定票集。", oneRequest: "轮次记录一次已接受的 VRF 请求。", seedWarning: "Seren 永远不会索要助记词或私钥。", transferWarning: "直接向合约转 POL 不能代替通过指定函数购票。" },
  },
  hi: {
    core: { eyebrow: "लाइव ऑन-चेन समारोह", title: "Seren राउंड कोर", status: { disconnected: "वॉलेट डिस्कनेक्ट", connecting: "वॉलेट कनेक्ट हो रहा है", wrongNetwork: "गलत नेटवर्क", loading: "Polygon पढ़ा जा रहा है", rpcError: "RPC उपलब्ध नहीं", none: "नए राउंड की प्रतीक्षा", open: "टिकट बिक्री खुली", randomnessRequested: "Chainlink VRF की प्रतीक्षा", randomnessReady: "Randomness प्राप्त", finalized: "राउंड finalized" }, message: { disconnected: "Polygon Mainnet से कोर सिंक करने के लिए वॉलेट जोड़ें।", connecting: "वॉलेट से निजी कनेक्शन बन रहा है।", wrongNetwork: "लाइव राउंड पढ़ने के लिए Polygon Mainnet पर जाएँ।", loading: "बिना fallback values के verified contract पढ़ा जा रहा है।", rpcError: "वॉलेट RPC मौजूदा राउंड नहीं लौटा सका।", none: "नया राउंड खुलने तक कमल शांत रहता है।", open: "Confirmed टिकटों के साथ कोर ऊर्जा जुटाता है।", randomnessRequested: "बिक्री बंद है, टिकट सेट तय है और Chainlink की प्रतीक्षा है।", randomnessReady: "Verifiable randomness स्वीकार है; अगला चरण finalization है।", finalized: "दस winning ticket ID contract में स्थायी रूप से उपलब्ध हैं।" }, round: "राउंड", pool: "मौजूदा पूल", target: "लक्ष्य", tickets: "टिकट", price: "टिकट मूल्य", verifiedSource: "आपके वॉलेट से सिंक · Polygon Mainnet" },
    lifecycle: { eyebrow: "Contract state map", title: "राउंड lifecycle", intro: "On-chain पुष्टि के बाद ही चरण आगे बढ़ता है।", current: "मौजूदा", completed: "पूरा", future: "आगामी", stages: [{ title: "बिक्री", body: "OPEN में exact contract quote से खरीद उपलब्ध है।" }, { title: "बंद होना", body: "Authorized admin draw प्रक्रिया शुरू करता है।" }, { title: "Chainlink VRF", body: "तय टिकट सेट एक verifiable request की प्रतीक्षा करता है।" }, { title: "Finalization", body: "Accepted randomness दस ordered ticket ID बनाता है।" }, { title: "Prize claim", body: "विजेता टिकट-मालिक wallet से prize claim करता है।" }] },
    participation: { share: "आपके टिकट इस राउंड के कुल टिकटों का {percent}% हैं।", shareUnavailable: "दोनों contract values पढ़ने के बाद ही हिस्सा दिखता है।", currentRound: "मौजूदा राउंड" },
    reveal: { eyebrow: "Polygon पर confirmed", title: "राउंड परिणाम सामने हैं", intro: "Interface contract order को नहीं बदलता।", skip: "सभी परिणाम दिखाएँ", complete: "दसों on-chain positions उपलब्ध हैं", claim: "उपलब्ध prize claim करें", verify: "Address सत्यापित करें" },
    proof: { eyebrow: "Proof Explorer", title: "हर चरण सत्यापित करें", intro: "Project के दावे पर भरोसा जरूरी नहीं—हर उपलब्ध चरण जाँचें।", available: "Confirmed evidence", awaiting: "अभी confirmed नहीं", event: "Contract event", stages: [{ title: "टिकट खरीद", body: "Confirmed buyTickets transaction ने ownership बनाई।" }, { title: "बिक्री बंद", body: "VRF request ने eligible ticket set तय किया।" }, { title: "Chainlink request", body: "Contract ने request ID emit किया।" }, { title: "Chainlink callback", body: "Lottery contract ने callback स्वीकार किया।" }, { title: "Finalization", body: "राउंड on-chain finalized हुआ।" }, { title: "Winning ticket ID", body: "WinnerSelected ordered IDs रखता है।" }, { title: "Prize allocation", body: "Results exact prize दिखाते हैं।" }, { title: "Claim", body: "PrizeClaimed self-service payout साबित करता है।" }] },
    security: { eyebrow: "Security Center", title: "हर interaction समझें", intro: "Verifiable facts, risk-free होने का दावा नहीं।", network: "नेटवर्क", contract: "मुख्य contract", source: "Source status", sourceValue: "Source code published और verified", vrf: "Randomness", audit: "External audit", auditValue: "Independent audit का दावा नहीं", admin: "Admin model", adminValue: "Authorized admins draw शुरू करते हैं; contract states लागू करता है।", target: "Target pool अपने आप draw शुरू नहीं करता।", fixedTickets: "requestDraw के बाद sales बंद और ticket set fixed है।", oneRequest: "राउंड एक accepted VRF request दर्ज करता है।", seedWarning: "Seren कभी seed phrase या private key नहीं माँगता।", transferWarning: "Contract को सीधा POL transfer टिकट खरीद का विकल्प नहीं है।" },
  },
  ar: {
    core: { eyebrow: "مراسم مباشرة على السلسلة", title: "نواة جولة Seren", status: { disconnected: "المحفظة غير متصلة", connecting: "جارٍ ربط المحفظة", wrongNetwork: "شبكة خاطئة", loading: "قراءة Polygon", rpcError: "RPC غير متاح", none: "انتظار جولة جديدة", open: "بيع التذاكر مفتوح", randomnessRequested: "انتظار Chainlink VRF", randomnessReady: "وصلت العشوائية", finalized: "اكتملت الجولة" }, message: { disconnected: "اربط محفظة لمزامنة النواة مع شبكة Polygon الرئيسية.", connecting: "جارٍ إنشاء اتصال خاص بالمحفظة.", wrongNetwork: "انتقل إلى Polygon Mainnet لقراءة الجولة.", loading: "جارٍ قراءة العقد الموثق دون قيم بديلة.", rpcError: "تعذر على RPC إعادة الجولة الحالية.", none: "تبقى زهرة اللوتس هادئة حتى يفتح العقد جولة جديدة.", open: "تتجمع الطاقة مع كل تذكرة مؤكدة.", randomnessRequested: "أُغلقت المبيعات وثبتت التذاكر بانتظار Chainlink.", randomnessReady: "قُبلت العشوائية القابلة للتحقق والخطوة التالية هي الإنهاء.", finalized: "أرقام التذاكر العشرة الفائزة محفوظة دائماً في العقد." }, round: "الجولة", pool: "المجمع الحالي", target: "الهدف", tickets: "التذاكر", price: "سعر التذكرة", verifiedSource: "مزامنة عبر محفظتك · Polygon Mainnet" },
    lifecycle: { eyebrow: "خريطة حالة العقد", title: "دورة الجولة", intro: "لا تتقدم المرحلة إلا بعد تأكيدها على السلسلة.", current: "الحالية", completed: "مكتملة", future: "قادمة", stages: [{ title: "المبيعات", body: "تسمح OPEN بالشراء وفق السعر الدقيق من العقد." }, { title: "الإغلاق", body: "يبدأ مسؤول مخول عملية السحب." }, { title: "Chainlink VRF", body: "تنتظر مجموعة التذاكر الثابتة طلب عشوائية واحداً." }, { title: "الإنهاء", body: "تنتج العشوائية المقبولة عشرة أرقام مرتبة." }, { title: "المطالبة", body: "يطالب الفائز من المحفظة المالكة للتذكرة." }] },
    participation: { share: "تمثل تذاكرك {percent}% من إجمالي تذاكر الجولة.", shareUnavailable: "تظهر النسبة بعد قراءة القيمتين من العقد.", currentRound: "الجولة الحالية" },
    reveal: { eyebrow: "مؤكد على Polygon", title: "كُشفت نتائج الجولة", intro: "تحافظ الواجهة على ترتيب العقد ولا تعيد خلط النتائج.", skip: "عرض كل النتائج", complete: "المراكز العشرة متاحة على السلسلة", claim: "المطالبة بالجائزة", verify: "تحقق من العنوان" },
    proof: { eyebrow: "مستكشف الإثبات", title: "تحقق من كل مرحلة", intro: "لا تحتاج إلى الثقة بتصريحات المشروع؛ تحقق من كل مرحلة متاحة.", available: "دليل مؤكد", awaiting: "غير مؤكد بعد", event: "حدث العقد", stages: [{ title: "شراء التذكرة", body: "أكدت معاملة buyTickets الملكية." }, { title: "إغلاق المبيعات", body: "ثبت طلب VRF التذاكر المؤهلة." }, { title: "طلب Chainlink", body: "أصدر العقد رقم الطلب." }, { title: "رد Chainlink", body: "قبل العقد رد المنسق." }, { title: "الإنهاء", body: "اكتملت الجولة بمعاملة مؤكدة." }, { title: "التذاكر الفائزة", body: "تحفظ WinnerSelected الأرقام المرتبة." }, { title: "تخصيص الجوائز", body: "تعرض النتائج كل جائزة دقيقة." }, { title: "المطالبة", body: "تثبت PrizeClaimed الدفع الذاتي." }] },
    security: { eyebrow: "مركز الأمان", title: "افهم تفاعل محفظتك", intro: "حقائق قابلة للتحقق وليست وعداً بانعدام المخاطر.", network: "الشبكة", contract: "العقد الرئيسي", source: "حالة المصدر", sourceValue: "الشفرة منشورة وموثقة", vrf: "العشوائية", audit: "التدقيق الخارجي", auditValue: "لا يُدعى وجود تدقيق مستقل", admin: "نموذج الإدارة", adminValue: "يبدأ المسؤولون المخولون السحب ويفرض العقد انتقال الحالات.", target: "المجمع المستهدف لا يبدأ السحب تلقائياً.", fixedTickets: "بعد requestDraw تُغلق المبيعات وتثبت التذاكر.", oneRequest: "تسجل الجولة طلب VRF مقبولاً واحداً.", seedWarning: "لا يطلب Seren أبداً عبارة الاسترداد أو المفتاح الخاص.", transferWarning: "تحويل POL مباشرة إلى العقد لا يستبدل الشراء عبر الوظيفة المخصصة." },
  },
  fr: {
    core: { eyebrow: "Cérémonie on-chain en direct", title: "Cœur du round Seren", status: { disconnected: "Wallet déconnecté", connecting: "Connexion du wallet", wrongNetwork: "Mauvais réseau", loading: "Lecture de Polygon", rpcError: "RPC indisponible", none: "Attente d’un nouveau round", open: "Vente ouverte", randomnessRequested: "Attente de Chainlink VRF", randomnessReady: "Aléa reçu", finalized: "Round finalisé" }, message: { disconnected: "Connectez un wallet pour synchroniser le cœur avec Polygon Mainnet.", connecting: "Établissement d’une connexion privée au wallet.", wrongNetwork: "Passez sur Polygon Mainnet pour lire le round.", loading: "Lecture du contrat vérifié sans valeur de secours.", rpcError: "Le RPC n’a pas renvoyé le round actuel.", none: "Le lotus reste calme jusqu’à l’ouverture d’un nouveau round.", open: "Le cœur gagne en énergie avec chaque ticket confirmé.", randomnessRequested: "Ventes closes, tickets figés, attente de Chainlink.", randomnessReady: "Aléa vérifiable accepté ; la finalisation est la prochaine étape.", finalized: "Les dix IDs gagnants restent disponibles dans le contrat." }, round: "Round", pool: "Cagnotte actuelle", target: "Cible", tickets: "Tickets", price: "Prix du ticket", verifiedSource: "Synchronisé via votre wallet · Polygon Mainnet" },
    lifecycle: { eyebrow: "Carte du contrat", title: "Cycle du round", intro: "Une étape avance uniquement après confirmation on-chain.", current: "Actuelle", completed: "Terminée", future: "À venir", stages: [{ title: "Ventes", body: "OPEN permet les achats avec le devis exact du contrat." }, { title: "Fermeture", body: "Un administrateur autorisé lance le processus." }, { title: "Chainlink VRF", body: "Les tickets figés attendent une requête vérifiable." }, { title: "Finalisation", body: "L’aléa accepté produit dix IDs ordonnés." }, { title: "Réclamation", body: "Le gagnant réclame depuis le wallet propriétaire." }] },
    participation: { share: "Vos tickets représentent {percent}% des tickets de ce round.", shareUnavailable: "La part apparaît après lecture des deux valeurs du contrat.", currentRound: "Round actuel" },
    reveal: { eyebrow: "Confirmé sur Polygon", title: "Le round est révélé", intro: "L’interface conserve l’ordre du contrat sans mélanger les résultats.", skip: "Afficher tous les résultats", complete: "Les dix positions on-chain sont visibles", claim: "Réclamer le prix disponible", verify: "Vérifier l’adresse" },
    proof: { eyebrow: "Explorateur de preuves", title: "Vérifiez chaque étape", intro: "Aucune confiance dans les affirmations n’est nécessaire : vérifiez chaque étape.", available: "Preuve confirmée", awaiting: "Pas encore confirmée", event: "Événement du contrat", stages: [{ title: "Achat", body: "Une transaction buyTickets a créé la propriété." }, { title: "Fermeture", body: "La requête VRF a figé les tickets éligibles." }, { title: "Requête Chainlink", body: "Le contrat a émis l’ID de requête." }, { title: "Callback Chainlink", body: "Le contrat a accepté le callback." }, { title: "Finalisation", body: "Le round a été finalisé on-chain." }, { title: "Tickets gagnants", body: "WinnerSelected conserve les IDs ordonnés." }, { title: "Allocation", body: "Les résultats exposent chaque prix exact." }, { title: "Réclamation", body: "PrizeClaimed prouve le paiement autonome." }] },
    security: { eyebrow: "Centre de sécurité", title: "Comprenez chaque interaction", intro: "Des faits vérifiables, pas une promesse d’absence de risque.", network: "Réseau", contract: "Contrat principal", source: "Code source", sourceValue: "Code publié et vérifié", vrf: "Aléa", audit: "Audit externe", auditValue: "Aucun audit indépendant n’est revendiqué", admin: "Modèle admin", adminValue: "Les admins autorisés lancent le tirage ; le contrat impose les états.", target: "La cagnotte cible ne lance pas automatiquement le tirage.", fixedTickets: "Après requestDraw, les ventes ferment et les tickets sont figés.", oneRequest: "Le round enregistre une requête VRF acceptée.", seedWarning: "Seren ne demande jamais de phrase de récupération ni de clé privée.", transferWarning: "Un transfert POL direct ne remplace pas l’achat via la fonction prévue." },
  },
  pt: {
    core: { eyebrow: "Cerimônia on-chain ao vivo", title: "Núcleo da rodada Seren", status: { disconnected: "Carteira desconectada", connecting: "Conectando carteira", wrongNetwork: "Rede incorreta", loading: "Lendo Polygon", rpcError: "RPC indisponível", none: "Aguardando nova rodada", open: "Venda aberta", randomnessRequested: "Aguardando Chainlink VRF", randomnessReady: "Aleatoriedade recebida", finalized: "Rodada finalizada" }, message: { disconnected: "Conecte uma carteira para sincronizar com a Polygon Mainnet.", connecting: "Criando conexão privada com a carteira.", wrongNetwork: "Mude para Polygon Mainnet para ler a rodada.", loading: "Lendo o contrato verificado sem valores alternativos.", rpcError: "O RPC não retornou a rodada atual.", none: "O lótus permanece calmo até uma nova rodada.", open: "O núcleo acumula energia com cada bilhete confirmado.", randomnessRequested: "Vendas fechadas e bilhetes fixados enquanto a Chainlink responde.", randomnessReady: "Aleatoriedade verificável aceita; falta a finalização.", finalized: "Os dez IDs vencedores permanecem disponíveis no contrato." }, round: "Rodada", pool: "Fundo atual", target: "Alvo", tickets: "Bilhetes", price: "Preço", verifiedSource: "Sincronizado pela carteira · Polygon Mainnet" },
    lifecycle: { eyebrow: "Mapa do contrato", title: "Ciclo da rodada", intro: "Uma etapa avança somente após confirmação on-chain.", current: "Atual", completed: "Concluída", future: "Futura", stages: [{ title: "Vendas", body: "OPEN permite compras pela cotação exata." }, { title: "Fechamento", body: "Um administrador autorizado inicia o sorteio." }, { title: "Chainlink VRF", body: "Os bilhetes fixos aguardam uma solicitação verificável." }, { title: "Finalização", body: "A aleatoriedade aceita produz dez IDs ordenados." }, { title: "Resgate", body: "O vencedor resgata pela carteira proprietária." }] },
    participation: { share: "Seus bilhetes representam {percent}% do total desta rodada.", shareUnavailable: "A participação aparece após ler os dois valores do contrato.", currentRound: "Rodada atual" },
    reveal: { eyebrow: "Confirmado na Polygon", title: "A rodada foi revelada", intro: "A interface preserva a ordem do contrato sem embaralhar resultados.", skip: "Mostrar todos", complete: "As dez posições on-chain estão visíveis", claim: "Resgatar prêmio disponível", verify: "Verificar endereço" },
    proof: { eyebrow: "Explorador de provas", title: "Verifique cada etapa", intro: "Você não precisa confiar em declarações: verifique cada etapa disponível.", available: "Prova confirmada", awaiting: "Ainda não confirmada", event: "Evento do contrato", stages: [{ title: "Compra", body: "Uma transação buyTickets confirmou a propriedade." }, { title: "Fechamento", body: "A solicitação VRF fixou os bilhetes elegíveis." }, { title: "Solicitação Chainlink", body: "O contrato emitiu o ID da solicitação." }, { title: "Callback Chainlink", body: "O contrato aceitou o callback." }, { title: "Finalização", body: "A rodada foi finalizada on-chain." }, { title: "Bilhetes vencedores", body: "WinnerSelected preserva os IDs ordenados." }, { title: "Alocação", body: "Os resultados expõem cada prêmio exato." }, { title: "Resgate", body: "PrizeClaimed prova o pagamento autônomo." }] },
    security: { eyebrow: "Centro de segurança", title: "Entenda cada interação", intro: "Fatos verificáveis, não promessa de ausência de risco.", network: "Rede", contract: "Contrato principal", source: "Código-fonte", sourceValue: "Código publicado e verificado", vrf: "Aleatoriedade", audit: "Auditoria externa", auditValue: "Nenhuma auditoria independente é alegada", admin: "Modelo admin", adminValue: "Admins autorizados iniciam o sorteio; o contrato aplica os estados.", target: "O fundo-alvo não inicia o sorteio automaticamente.", fixedTickets: "Após requestDraw, as vendas fecham e os bilhetes são fixados.", oneRequest: "A rodada registra uma solicitação VRF aceita.", seedWarning: "A Seren nunca pede seed phrase ou chave privada.", transferWarning: "Transferir POL diretamente não substitui a compra pela função prevista." },
  },
};
