import type { Locale } from "@/i18n/locales";

export type ExperienceContent = {
  pool: {
    currentOfTarget: string;
    filled: string;
    remaining: string;
    source: string;
    lastBlock: string;
    informational: string;
    connect: string;
    connecting: string;
    wrongNetwork: string;
    loading: string;
    unavailable: string;
    rpcError: string;
    contractError: string;
  };
  oracle: {
    eyebrow: string;
    title: string;
    intro: string;
    trigger: string;
    generating: string;
    prediction: string;
    luckyNumber: string;
    symbol: string;
    close: string;
    share: string;
    newPrediction: string;
    shared: string;
    disclaimer: string;
    messages: readonly string[];
    symbols: readonly string[];
  };
  securityWarning: string;
  mobile: { buy: string; connect: string };
  winners: { uniqueTickets: string; repeatedWallet: string; rules: string; onchain: string };
  activity: { block: string; transaction: string };
};

export const experienceContent: Record<Locale, ExperienceContent> = {
  en: {
    pool: { currentOfTarget: "{current} of {target}", filled: "{percent}% filled", remaining: "Remaining to target: {amount}", source: "Source: Polygon Mainnet", lastBlock: "Updated at block {block}", informational: "The target pool is an informational reference and does not trigger a draw automatically.", connect: "Connect a wallet to load current round data from Polygon.", connecting: "Connecting to your wallet…", wrongNetwork: "Switch to Polygon Mainnet to load the current round.", loading: "Reading the latest round from Polygon…", unavailable: "No active round is currently available.", rpcError: "The wallet RPC could not load the round. Try again.", contractError: "The contract read failed. No fallback values were substituted." },
    oracle: { eyebrow: "A local moment of serendipity", title: "Seren Oracle", intro: "Reveal an entertainment-only prediction created privately in your browser.", trigger: "Get a prediction", generating: "The lotus is reading the moment…", prediction: "Your prediction", luckyNumber: "Lucky number", symbol: "Symbol of the day", close: "Close", share: "Share", newPrediction: "Get a new prediction", shared: "Prediction ready to share", disclaimer: "This prediction is entertainment only. It does not affect the draw, winning probability or smart-contract operation.", messages: ["Quiet choices may reveal the clearest path today.", "A patient step can open an unexpected door.", "Look twice: a small detail may carry meaning.", "A new connection may brighten the next chapter.", "Steady progress matters more than sudden motion.", "The chain remembers actions made with intention.", "Curiosity will lead you toward a useful discovery.", "Calm attention is your strongest signal today.", "A growing lotus favors thoughtful beginnings.", "The next block may hold a welcome surprise."], symbols: ["Growing lotus", "Violet orbit", "Silver key", "Polygon star", "Open circle"] },
    securityWarning: "Seren never asks for a seed phrase or private key.",
    mobile: { buy: "Buy", connect: "Connect wallet" },
    winners: { uniqueTickets: "Ten unique ticket IDs are selected, not necessarily ten different wallet addresses.", repeatedWallet: "One wallet can win more than once when it owns multiple selected tickets.", rules: "Prize rules", onchain: "Final on-chain results" },
    activity: { block: "Block", transaction: "Transaction" },
  },
  ru: {
    pool: { currentOfTarget: "{current} из {target}", filled: "Заполнено: {percent}%", remaining: "До целевого фонда: {amount}", source: "Источник: Polygon Mainnet", lastBlock: "Обновлено на блоке {block}", informational: "Целевой фонд является информационным ориентиром и не запускает розыгрыш автоматически.", connect: "Подключите кошелёк, чтобы загрузить актуальные данные раунда из Polygon.", connecting: "Подключение к кошельку…", wrongNetwork: "Переключитесь на Polygon Mainnet, чтобы загрузить текущий раунд.", loading: "Читаем актуальный раунд из Polygon…", unavailable: "Активный раунд сейчас недоступен.", rpcError: "RPC кошелька не загрузил раунд. Попробуйте ещё раз.", contractError: "Чтение контракта завершилось ошибкой. Подставные значения не используются." },
    oracle: { eyebrow: "Локальный момент удачи", title: "Оракул Seren", intro: "Получите развлекательное предсказание, которое создаётся приватно в вашем браузере.", trigger: "Получить предсказание", generating: "Лотос прислушивается к моменту…", prediction: "Ваше предсказание", luckyNumber: "Счастливое число", symbol: "Символ дня", close: "Закрыть", share: "Поделиться", newPrediction: "Получить новое предсказание", shared: "Предсказание готово к отправке", disclaimer: "Предсказание является развлекательной функцией и не влияет на ход розыгрыша, вероятность выигрыша или работу смарт-контракта.", messages: ["Сегодня удача любит тех, кто принимает решения спокойно.", "Цепочка хранит неожиданный поворот.", "Небольшая деталь сегодня может оказаться значимой.", "Новая связь осветит следующую главу.", "Спокойный шаг важнее резкого движения.", "Блокчейн помнит поступки, сделанные осознанно.", "Любопытство приведёт к полезному открытию.", "Внимательность сегодня — ваш лучший ориентир.", "Растущий лотос благоволит новым начинаниям.", "Следующий блок может принести приятный сюрприз."], symbols: ["Растущий лотос", "Фиолетовая орбита", "Серебряный ключ", "Звезда Polygon", "Открытый круг"] },
    securityWarning: "Seren никогда не запрашивает seed-фразу или private key.",
    mobile: { buy: "Купить", connect: "Подключить кошелёк" },
    winners: { uniqueTickets: "Выбираются десять уникальных ticket ID, а не обязательно десять разных адресов.", repeatedWallet: "Один адрес может выиграть несколько раз, если ему принадлежат разные выбранные билеты.", rules: "Правила распределения", onchain: "Финальные on-chain результаты" },
    activity: { block: "Блок", transaction: "Транзакция" },
  },
  es: {
    pool: { currentOfTarget: "{current} de {target}", filled: "{percent}% completado", remaining: "Falta para el objetivo: {amount}", source: "Fuente: Polygon Mainnet", lastBlock: "Actualizado en el bloque {block}", informational: "El fondo objetivo es una referencia informativa y no inicia el sorteo automáticamente.", connect: "Conecta una cartera para cargar la ronda actual desde Polygon.", connecting: "Conectando la cartera…", wrongNetwork: "Cambia a Polygon Mainnet para cargar la ronda.", loading: "Leyendo la ronda más reciente de Polygon…", unavailable: "No hay una ronda activa disponible.", rpcError: "El RPC de la cartera no pudo cargar la ronda.", contractError: "Falló la lectura del contrato. No se muestran valores alternativos." },
    oracle: { eyebrow: "Un instante local de fortuna", title: "Oráculo Seren", intro: "Descubre una predicción de entretenimiento creada de forma privada en tu navegador.", trigger: "Obtener predicción", generating: "El loto escucha el momento…", prediction: "Tu predicción", luckyNumber: "Número de la suerte", symbol: "Símbolo del día", close: "Cerrar", share: "Compartir", newPrediction: "Nueva predicción", shared: "Predicción lista para compartir", disclaimer: "La predicción es solo entretenimiento y no afecta al sorteo, las probabilidades ni el contrato.", messages: ["Las decisiones tranquilas revelan hoy el camino más claro.", "Un paso paciente puede abrir una puerta inesperada.", "Mira dos veces: un detalle pequeño puede importar.", "Una nueva conexión iluminará el próximo capítulo.", "El progreso constante vale más que un impulso repentino.", "La cadena recuerda las acciones hechas con intención.", "La curiosidad te llevará a un hallazgo útil.", "La atención serena es hoy tu mejor señal.", "Un loto creciente favorece los nuevos comienzos.", "El próximo bloque puede guardar una sorpresa amable."], symbols: ["Loto creciente", "Órbita violeta", "Llave plateada", "Estrella Polygon", "Círculo abierto"] },
    securityWarning: "Seren nunca solicita una frase semilla ni una clave privada.", mobile: { buy: "Comprar", connect: "Conectar cartera" }, winners: { uniqueTickets: "Se eligen diez ID de boleto únicos, no necesariamente diez carteras distintas.", repeatedWallet: "Una cartera puede ganar varias veces si posee varios boletos seleccionados.", rules: "Reglas de premios", onchain: "Resultados finales on-chain" }, activity: { block: "Bloque", transaction: "Transacción" },
  },
  zh: {
    pool: { currentOfTarget: "{current} / {target}", filled: "已完成 {percent}%", remaining: "距离目标：{amount}", source: "来源：Polygon 主网", lastBlock: "更新于区块 {block}", informational: "目标奖池仅供参考，不会自动触发开奖。", connect: "连接钱包以从 Polygon 加载当前轮次数据。", connecting: "正在连接钱包…", wrongNetwork: "请切换到 Polygon 主网。", loading: "正在读取 Polygon 最新轮次…", unavailable: "当前没有可用的活动轮次。", rpcError: "钱包 RPC 无法加载轮次，请重试。", contractError: "合约读取失败，未使用备用演示数据。" },
    oracle: { eyebrow: "浏览器中的幸运时刻", title: "Seren 神谕", intro: "在浏览器中私密生成一条仅供娱乐的预测。", trigger: "获取预测", generating: "莲花正在感知此刻…", prediction: "你的预测", luckyNumber: "幸运数字", symbol: "今日符号", close: "关闭", share: "分享", newPrediction: "新的预测", shared: "预测已可分享", disclaimer: "预测仅供娱乐，不影响开奖、中奖概率或智能合约运行。", messages: ["平静的选择会显露清晰的方向。", "耐心的一步可能开启意外之门。", "再看一眼，小细节也许很重要。", "新的连接会照亮下一章节。", "稳定前进胜过突然冲动。", "链会记住每一次有意的行动。", "好奇心将带来有用的发现。", "专注是今天最可靠的信号。", "成长的莲花眷顾新的开始。", "下一个区块可能藏着温柔惊喜。"], symbols: ["成长莲花", "紫色轨道", "银色钥匙", "Polygon 星", "开放之环"] },
    securityWarning: "Seren 绝不会索要助记词或私钥。", mobile: { buy: "购买", connect: "连接钱包" }, winners: { uniqueTickets: "选出的是十个唯一票号，不一定是十个不同钱包。", repeatedWallet: "若一个钱包拥有多张被选中的票，它可以多次中奖。", rules: "奖金规则", onchain: "最终链上结果" }, activity: { block: "区块", transaction: "交易" },
  },
  hi: {
    pool: { currentOfTarget: "{target} में से {current}", filled: "{percent}% पूरा", remaining: "लक्ष्य तक शेष: {amount}", source: "स्रोत: Polygon Mainnet", lastBlock: "ब्लॉक {block} पर अपडेट", informational: "लक्ष्य पूल केवल सूचना है और अपने आप ड्रॉ शुरू नहीं करता।", connect: "Polygon से मौजूदा राउंड डेटा लोड करने के लिए वॉलेट जोड़ें।", connecting: "वॉलेट कनेक्ट हो रहा है…", wrongNetwork: "Polygon Mainnet पर जाएँ।", loading: "Polygon से नवीनतम राउंड पढ़ा जा रहा है…", unavailable: "अभी कोई सक्रिय राउंड उपलब्ध नहीं है।", rpcError: "वॉलेट RPC राउंड लोड नहीं कर सका।", contractError: "कॉन्ट्रैक्ट रीड विफल हुआ; कोई अनुमानित मान नहीं दिखाया गया।" },
    oracle: { eyebrow: "ब्राउज़र में सौभाग्य का पल", title: "Seren Oracle", intro: "अपने ब्राउज़र में निजी रूप से बना मनोरंजन-केवल संकेत देखें।", trigger: "संकेत पाएँ", generating: "कमल इस पल को सुन रहा है…", prediction: "आपका संकेत", luckyNumber: "शुभ अंक", symbol: "आज का प्रतीक", close: "बंद करें", share: "साझा करें", newPrediction: "नया संकेत", shared: "संकेत साझा करने के लिए तैयार", disclaimer: "यह संकेत केवल मनोरंजन है और ड्रॉ, जीत की संभावना या स्मार्ट कॉन्ट्रैक्ट को प्रभावित नहीं करता।", messages: ["शांत निर्णय आज साफ रास्ता दिखा सकते हैं।", "धैर्य का एक कदम अनपेक्षित द्वार खोल सकता है।", "दोबारा देखें; छोटी बात अर्थपूर्ण हो सकती है।", "नया संबंध अगला अध्याय रोशन करेगा।", "स्थिर प्रगति अचानक गति से अधिक मायने रखती है।", "चेन सोच-समझकर किए काम याद रखती है।", "जिज्ञासा उपयोगी खोज तक ले जाएगी।", "शांत ध्यान आज आपका मजबूत संकेत है।", "बढ़ता कमल नई शुरुआत का साथ देता है।", "अगला ब्लॉक सुखद आश्चर्य ला सकता है।"], symbols: ["बढ़ता कमल", "बैंगनी कक्षा", "चाँदी की चाबी", "Polygon तारा", "खुला वृत्त"] },
    securityWarning: "Seren कभी seed phrase या private key नहीं माँगता।", mobile: { buy: "खरीदें", connect: "वॉलेट जोड़ें" }, winners: { uniqueTickets: "दस unique ticket ID चुने जाते हैं, जरूरी नहीं कि दस अलग wallet हों।", repeatedWallet: "एक wallet कई बार जीत सकता है यदि उसके कई टिकट चुने जाएँ।", rules: "पुरस्कार नियम", onchain: "अंतिम on-chain परिणाम" }, activity: { block: "ब्लॉक", transaction: "ट्रांज़ैक्शन" },
  },
  ar: {
    pool: { currentOfTarget: "{current} من {target}", filled: "مكتمل بنسبة {percent}%", remaining: "المتبقي للهدف: {amount}", source: "المصدر: شبكة Polygon الرئيسية", lastBlock: "آخر تحديث عند الكتلة {block}", informational: "المجمع المستهدف مرجع معلوماتي ولا يبدأ السحب تلقائياً.", connect: "اربط محفظة لتحميل بيانات الجولة الحالية من Polygon.", connecting: "جارٍ ربط المحفظة…", wrongNetwork: "انتقل إلى شبكة Polygon الرئيسية.", loading: "جارٍ قراءة أحدث جولة من Polygon…", unavailable: "لا توجد جولة نشطة متاحة حالياً.", rpcError: "تعذر على RPC المحفظة تحميل الجولة.", contractError: "فشلت قراءة العقد ولم تُستخدم بيانات بديلة." },
    oracle: { eyebrow: "لحظة حظ محلية", title: "عرّاف Seren", intro: "اكشف تنبؤاً ترفيهياً يُنشأ بخصوصية داخل متصفحك.", trigger: "احصل على تنبؤ", generating: "زهرة اللوتس تصغي إلى اللحظة…", prediction: "تنبؤك", luckyNumber: "رقم الحظ", symbol: "رمز اليوم", close: "إغلاق", share: "مشاركة", newPrediction: "تنبؤ جديد", shared: "التنبؤ جاهز للمشاركة", disclaimer: "هذا التنبؤ للترفيه فقط ولا يؤثر في السحب أو احتمال الفوز أو عمل العقد الذكي.", messages: ["قد تكشف الخيارات الهادئة أوضح طريق اليوم.", "خطوة صبورة قد تفتح باباً غير متوقع.", "انظر مرتين؛ فقد يحمل تفصيل صغير معنى كبيراً.", "صلة جديدة قد تضيء الفصل القادم.", "التقدم الثابت أهم من الحركة المفاجئة.", "تتذكر السلسلة الأفعال المقصودة.", "سيقودك الفضول إلى اكتشاف مفيد.", "الانتباه الهادئ هو أقوى إشاراتك اليوم.", "لوتس نامٍ يساند البدايات المدروسة.", "قد تحمل الكتلة التالية مفاجأة لطيفة."], symbols: ["اللوتس النامي", "المدار البنفسجي", "المفتاح الفضي", "نجمة Polygon", "الدائرة المفتوحة"] },
    securityWarning: "لا يطلب Seren أبداً عبارة الاسترداد أو المفتاح الخاص.", mobile: { buy: "شراء", connect: "ربط المحفظة" }, winners: { uniqueTickets: "يتم اختيار عشرة أرقام تذاكر فريدة، وليس بالضرورة عشرة عناوين مختلفة.", repeatedWallet: "يمكن لمحفظة واحدة الفوز أكثر من مرة إذا امتلكت عدة تذاكر مختارة.", rules: "قواعد الجوائز", onchain: "النتائج النهائية على السلسلة" }, activity: { block: "الكتلة", transaction: "المعاملة" },
  },
  fr: {
    pool: { currentOfTarget: "{current} sur {target}", filled: "{percent}% rempli", remaining: "Reste avant l’objectif : {amount}", source: "Source : Polygon Mainnet", lastBlock: "Mis à jour au bloc {block}", informational: "La cagnotte cible est un repère informatif et ne déclenche pas automatiquement le tirage.", connect: "Connectez un wallet pour charger le round actuel depuis Polygon.", connecting: "Connexion du wallet…", wrongNetwork: "Passez sur Polygon Mainnet.", loading: "Lecture du dernier round sur Polygon…", unavailable: "Aucun round actif n’est disponible.", rpcError: "Le RPC du wallet n’a pas pu charger le round.", contractError: "La lecture du contrat a échoué, sans valeur de remplacement." },
    oracle: { eyebrow: "Un instant local de sérendipité", title: "Oracle Seren", intro: "Découvrez une prédiction ludique créée en privé dans votre navigateur.", trigger: "Obtenir une prédiction", generating: "Le lotus écoute l’instant…", prediction: "Votre prédiction", luckyNumber: "Nombre porte-bonheur", symbol: "Symbole du jour", close: "Fermer", share: "Partager", newPrediction: "Nouvelle prédiction", shared: "Prédiction prête à partager", disclaimer: "Cette prédiction est uniquement ludique et n’influence ni le tirage, ni les chances, ni le smart contract.", messages: ["Les choix calmes révèlent aujourd’hui le chemin le plus clair.", "Un pas patient peut ouvrir une porte inattendue.", "Regardez deux fois : un petit détail peut compter.", "Une nouvelle connexion éclairera le prochain chapitre.", "Un progrès régulier vaut mieux qu’un mouvement soudain.", "La chaîne se souvient des actions intentionnelles.", "La curiosité vous mènera vers une découverte utile.", "L’attention calme est votre meilleur signal aujourd’hui.", "Un lotus en croissance favorise les nouveaux départs.", "Le prochain bloc peut contenir une heureuse surprise."], symbols: ["Lotus en croissance", "Orbite violette", "Clé d’argent", "Étoile Polygon", "Cercle ouvert"] },
    securityWarning: "Seren ne demande jamais de phrase de récupération ni de clé privée.", mobile: { buy: "Acheter", connect: "Connecter le wallet" }, winners: { uniqueTickets: "Dix IDs de tickets uniques sont choisis, pas forcément dix wallets distincts.", repeatedWallet: "Un wallet peut gagner plusieurs fois s’il possède plusieurs tickets sélectionnés.", rules: "Règles des prix", onchain: "Résultats finaux on-chain" }, activity: { block: "Bloc", transaction: "Transaction" },
  },
  pt: {
    pool: { currentOfTarget: "{current} de {target}", filled: "{percent}% preenchido", remaining: "Falta para o alvo: {amount}", source: "Fonte: Polygon Mainnet", lastBlock: "Atualizado no bloco {block}", informational: "O fundo-alvo é uma referência informativa e não inicia o sorteio automaticamente.", connect: "Conecte uma carteira para carregar a rodada atual da Polygon.", connecting: "Conectando a carteira…", wrongNetwork: "Mude para Polygon Mainnet.", loading: "Lendo a rodada mais recente da Polygon…", unavailable: "Nenhuma rodada ativa está disponível.", rpcError: "O RPC da carteira não conseguiu carregar a rodada.", contractError: "A leitura do contrato falhou; nenhum valor alternativo foi usado." },
    oracle: { eyebrow: "Um instante local de sorte", title: "Oráculo Seren", intro: "Revele uma previsão de entretenimento criada com privacidade no navegador.", trigger: "Obter previsão", generating: "O lótus está ouvindo o momento…", prediction: "Sua previsão", luckyNumber: "Número da sorte", symbol: "Símbolo do dia", close: "Fechar", share: "Compartilhar", newPrediction: "Nova previsão", shared: "Previsão pronta para compartilhar", disclaimer: "Esta previsão é apenas entretenimento e não afeta o sorteio, as chances ou o contrato inteligente.", messages: ["Escolhas tranquilas podem revelar o caminho mais claro hoje.", "Um passo paciente pode abrir uma porta inesperada.", "Olhe duas vezes: um detalhe pequeno pode importar.", "Uma nova conexão iluminará o próximo capítulo.", "Progresso constante vale mais que um impulso repentino.", "A blockchain lembra ações feitas com intenção.", "A curiosidade levará a uma descoberta útil.", "A atenção calma é seu sinal mais forte hoje.", "Um lótus crescente favorece novos começos.", "O próximo bloco pode guardar uma surpresa gentil."], symbols: ["Lótus crescente", "Órbita violeta", "Chave de prata", "Estrela Polygon", "Círculo aberto"] },
    securityWarning: "A Seren nunca pede seed phrase ou chave privada.", mobile: { buy: "Comprar", connect: "Conectar carteira" }, winners: { uniqueTickets: "São escolhidos dez IDs de bilhete únicos, não necessariamente dez carteiras diferentes.", repeatedWallet: "Uma carteira pode vencer mais de uma vez se possuir vários bilhetes selecionados.", rules: "Regras dos prêmios", onchain: "Resultados finais on-chain" }, activity: { block: "Bloco", transaction: "Transação" },
  },
};
