import type { Locale } from "@/i18n/locales";

type Step = { title: string; body: string };
type Faq = { question: string; answer: string };

export type SiteContent = {
  metadata: { title: string; description: string };
  nav: { home: string; lottery: string; how: string; winners: string; transparency: string; faq: string };
  language: string;
  hero: { eyebrow: string; title: string; description: string; primary: string; secondary: string; note: string };
  trust: string[];
  how: { eyebrow: string; title: string; intro: string; steps: Step[] };
  prizes: { eyebrow: string; title: string; body: string; first: string; others: string; note: string };
  referral: { eyebrow: string; title: string; body: string; points: string[] };
  account: { eyebrow: string; title: string; body: string; points: string[] };
  transparency: { eyebrow: string; title: string; body: string; points: string[]; contract: string };
  faq: { eyebrow: string; title: string; intro: string; items: Faq[] };
  final: { title: string; body: string; primary: string; secondary: string };
  footer: { tagline: string; navigation: string; resources: string; contract: string; risk: string; rights: string };
};
export const siteContent: Record<Locale, SiteContent> = {
  en: {
    metadata: { title: "Transparent on-chain lottery on Polygon", description: "Seren Lottery Chain is a transparent Polygon lottery with contract-priced tickets, Chainlink VRF v2.5 randomness, ten winning ticket IDs and self-service prize claims." },
    nav: { home: "Home", lottery: "Lottery", how: "How it works", winners: "Winners", transparency: "Transparency", faq: "FAQ" },
    language: "Language",
    hero: { eyebrow: "TRANSPARENT ON-CHAIN DRAW ON POLYGON", title: "Fortune becomes a blockchain event", description: "Ten winning tickets. Verifiable Chainlink VRF v2.5 randomness. Every stage and result can be checked independently.", primary: "Enter the round", secondary: "Verify fairness", note: "Participation involves risk. No profit is guaranteed." },
    trust: ["Polygon Mainnet", "Chainlink VRF v2.5", "Verified Contract", "10 Winning Tickets", "Direct Claim", "No Project Token"],
    how: { eyebrow: "Clear from wallet to claim", title: "How Seren Lottery Chain works", intro: "The interface explains every step while the contract remains the source of truth for prices, round status and results.", steps: [
      { title: "Connect on Polygon", body: "Choose an injected wallet or WalletConnect and switch to Polygon Mainnet." },
      { title: "Choose 1–100 tickets", body: "Select a quantity, optional referral credits and a referrer on your first purchase." },
      { title: "Approve the exact quote", body: "The app simulates the contract call and asks your wallet to confirm the current quoted payment." },
      { title: "Verify and claim", body: "Chainlink VRF supplies randomness; finalized winners claim prizes from their own wallet." },
    ] },
    prizes: { eyebrow: "Ten winning positions", title: "More ways for a ticket to win", body: "Each finalized round selects ten unique winning ticket IDs. The contract records the winner, ticket ID, exact prize and claim status for every position.", first: "1st place receives the largest contract-calculated share", others: "Places 2–10 share the remaining prize allocation", note: "Exact payouts are read from finalized on-chain results; the target pool is informational and does not trigger a draw." },
    referral: { eyebrow: "Referral credits", title: "Bring a participant, unlock future value", body: "A valid referrer can be set only on a wallet’s first purchase and becomes permanent. Credits earned through the contract can reduce the price of eligible tickets.", points: ["Referrer must be a previous participant", "Self-referral is rejected", "One credit can buy one ticket at half price", "The contract validates every credit used"] },
    account: { eyebrow: "Personal lottery area", title: "Tickets, credits and claims in one place", body: "After connecting, your dashboard reads wallet-specific values directly through the selected wallet provider.", points: ["POL balance and current-round tickets", "Referral credit balance and fixed referrer", "Winning-round history", "Individual and batch prize claims"] },
    transparency: { eyebrow: "On-chain evidence", title: "Inspect the rules, randomness and results", body: "Seren exposes the verified contract, Polygon transactions, Chainlink VRF coordinator data and the lifecycle of every round.", points: ["Verified source code on PolygonScan", "No invented pool, price or winner values", "Exact quote simulation before a purchase", "Public event history from the deployment block"], contract: "Open verified contract" },
    faq: { eyebrow: "Questions, answered", title: "Frequently asked questions", intro: "Understand the mechanics and risks before connecting a wallet.", items: [
      { question: "What is Seren Lottery Chain?", answer: "It is a smart-contract lottery on Polygon where ticket purchases, draw state, winners and claims are verifiable on-chain." },
      { question: "Which network do I need?", answer: "Polygon Mainnet, chain ID 137. The app can request a network switch from a compatible wallet." },
      { question: "How is the ticket price determined?", answer: "The interface reads the current ticket price and an exact purchase quote from the verified contract." },
      { question: "How many tickets can I buy?", answer: "From 1 to 100 tickets in one confirmed purchase, subject to the current contract state." },
      { question: "Does reaching the target pool start the draw?", answer: "No. The target is informational. An authorized administrator starts the draw according to the contract process." },
      { question: "How is randomness generated?", answer: "The contract uses Chainlink VRF v2.5 to request verifiable randomness for the round." },
      { question: "How many winners are there?", answer: "Ten unique ticket IDs are selected for a finalized round." },
      { question: "Can one wallet win more than once?", answer: "Yes. A wallet holding multiple selected ticket IDs can occupy more than one winning position." },
      { question: "Are prizes transferred automatically?", answer: "No. A winner claims an available prize from the wallet that owns the winning ticket." },
      { question: "How does the referral program work?", answer: "A previous participant can be set as referrer on the first purchase; eligible activity can grant contract-managed credits." },
      { question: "Can I change my referrer?", answer: "No. Once registered by the first purchase, the referrer is permanent for that wallet." },
      { question: "What happens if my wallet is on the wrong network?", answer: "Live contract actions remain unavailable until the wallet switches to Polygon Mainnet." },
      { question: "Is participation an investment?", answer: "No. Lottery participation is risky, POL spent may be lost and no return or profit is guaranteed." },
    ] },
    final: { title: "Ready to inspect the current round?", body: "Connect only when you are comfortable with the rules and risk. Live values will come from the verified Polygon contract through your wallet.", primary: "Go to the lottery", secondary: "Read the contract" },
    footer: { tagline: "Transparent on-chain lottery on Polygon", navigation: "Navigation", resources: "Verification", contract: "Smart contract", risk: "The target pool is informational, project fees apply to ticket revenue, and participation does not guarantee profit.", rights: "© 2026 Seren Lottery Chain" },
  },
  ru: {
    metadata: { title: "Прозрачный on-chain розыгрыш в Polygon", description: "Seren Lottery Chain — прозрачный on-chain розыгрыш в Polygon с проверяемой случайностью Chainlink VRF v2.5, десятью выигрышными билетами и публично проверяемыми результатами." },
    nav: { home: "Главная", lottery: "Лотерея", how: "Как это работает", winners: "Победители", transparency: "Прозрачность", faq: "Вопросы" }, language: "Язык",
    hero: { eyebrow: "ПРОЗРАЧНЫЙ ON-CHAIN РОЗЫГРЫШ В POLYGON", title: "Удача становится событием блокчейна", description: "Десять выигрышных билетов. Проверяемая случайность Chainlink VRF v2.5. Каждый этап и результат можно проверить самостоятельно.", primary: "Участвовать в раунде", secondary: "Проверить честность", note: "Участие связано с риском и не гарантирует прибыль." },
    trust: ["Polygon Mainnet", "Chainlink VRF v2.5", "Верифицированный контракт", "10 выигрышных билетов", "Прямой claim", "Без токена проекта"],
    how: { eyebrow: "От кошелька до приза", title: "Как работает Seren Lottery Chain", intro: "Интерфейс объясняет каждый шаг, а контракт остаётся единственным источником цены, статуса раунда и результатов.", steps: [
      { title: "Подключитесь к Polygon", body: "Выберите браузерный кошелёк или WalletConnect и перейдите в Polygon Mainnet." }, { title: "Выберите 1–100 билетов", body: "Укажите количество, referral credits и реферера при первой покупке." }, { title: "Подтвердите точный quote", body: "Приложение симулирует вызов и показывает актуальную сумму перед подтверждением в кошельке." }, { title: "Проверьте и получите", body: "Chainlink VRF даёт случайность, а победители сами получают доступные призы." },
    ] },
    prizes: { eyebrow: "Десять призовых мест", title: "Больше возможностей для выигрышного билета", body: "В завершённом раунде выбираются десять уникальных ticket ID. Контракт хранит победителя, номер билета, точный приз и статус получения для каждого места.", first: "1-е место получает крупнейшую долю по расчёту контракта", others: "Места 2–10 делят оставшееся призовое распределение", note: "Точные выплаты читаются из финальных on-chain результатов; целевой фонд носит информационный характер." },
    referral: { eyebrow: "Реферальная программа", title: "Приглашайте участников и получайте credits", body: "Реферер указывается только при первой покупке и закрепляется навсегда. Начисленные контрактом credits могут снизить цену подходящих билетов.", points: ["Реферер должен участвовать раньше", "Самореферал запрещён", "Один credit даёт один билет за полцены", "Каждый credit проверяется контрактом"] },
    account: { eyebrow: "Личный кабинет", title: "Билеты, credits и призы в одном месте", body: "После подключения dashboard читает данные вашего адреса напрямую через выбранный wallet provider.", points: ["Баланс POL и билеты текущего раунда", "Referral credits и закреплённый реферер", "История выигрышных раундов", "Одиночный и пакетный claim призов"] },
    transparency: { eyebrow: "On-chain доказательства", title: "Проверяйте правила, случайность и результаты", body: "Seren открывает доступ к верифицированному контракту, транзакциям Polygon, данным Chainlink VRF и жизненному циклу раунда.", points: ["Исходный код подтверждён в PolygonScan", "Без выдуманных цен, фондов и победителей", "Симуляция точного quote до покупки", "Публичная история событий с блока деплоя"], contract: "Открыть контракт" },
    faq: { eyebrow: "Главное до подключения", title: "Частые вопросы", intro: "Разберитесь в механике и рисках до подключения кошелька.", items: [
      { question: "Что такое Seren Lottery Chain?", answer: "Это лотерея на смарт-контракте Polygon, где покупки, статус розыгрыша, победители и получение призов проверяются on-chain." }, { question: "Какая сеть нужна?", answer: "Polygon Mainnet, chain ID 137. Совместимый кошелёк может переключить сеть по запросу сайта." }, { question: "Откуда берётся цена билета?", answer: "Интерфейс читает цену и точный quote покупки из верифицированного контракта." }, { question: "Сколько билетов можно купить?", answer: "От 1 до 100 билетов за одну подтверждённую покупку при разрешающем статусе контракта." }, { question: "Целевой фонд запускает розыгрыш?", answer: "Нет. Это информационный ориентир; розыгрыш запускает уполномоченный администратор по правилам контракта." }, { question: "Как создаётся случайность?", answer: "Контракт запрашивает проверяемую случайность у Chainlink VRF v2.5." }, { question: "Сколько победителей в раунде?", answer: "В финализированном раунде выбираются десять уникальных ticket ID." }, { question: "Один кошелёк может выиграть несколько раз?", answer: "Да, если у него находятся несколько выбранных билетов." }, { question: "Призы отправляются автоматически?", answer: "Нет. Победитель самостоятельно вызывает claim с кошелька, которому принадлежит билет." }, { question: "Как работает реферальная программа?", answer: "При первой покупке можно указать прошлого участника; подходящая активность начисляет credits по правилам контракта." }, { question: "Можно изменить реферера?", answer: "Нет. После регистрации первой покупкой реферер навсегда закрепляется за адресом." }, { question: "Что делать при неверной сети?", answer: "Переключить кошелёк на Polygon Mainnet; до этого live-данные и действия недоступны." }, { question: "Это инвестиция?", answer: "Нет. Участие рискованно, потраченные POL можно потерять, доходность и прибыль не гарантируются." },
    ] },
    final: { title: "Готовы проверить текущий раунд?", body: "Подключайтесь только после понимания правил и риска. Live-значения будут прочитаны из верифицированного Polygon-контракта через ваш кошелёк.", primary: "Перейти к лотерее", secondary: "Изучить контракт" },
    footer: { tagline: "Прозрачная on-chain лотерея в Polygon", navigation: "Навигация", resources: "Проверка", contract: "Смарт-контракт", risk: "Целевой фонд информационный, к выручке билетов применяется комиссия проекта, участие не гарантирует прибыль.", rights: "© 2026 Seren Lottery Chain" },
  },
  es: {
    metadata: { title: "Lotería on-chain transparente en Polygon", description: "Seren Lottery Chain ofrece precio desde el contrato, aleatoriedad Chainlink VRF v2.5, diez boletos ganadores y cobro autónomo de premios." },
    nav: { home: "Inicio", lottery: "Lotería", how: "Cómo funciona", winners: "Ganadores", transparency: "Transparencia", faq: "Preguntas" }, language: "Idioma",
    hero: { eyebrow: "SORTEO ON-CHAIN TRANSPARENTE EN POLYGON", title: "La fortuna se convierte en un evento blockchain", description: "Diez boletos ganadores, aleatoriedad verificable de Chainlink VRF v2.5 y cada etapa comprobable.", primary: "Participar en la ronda", secondary: "Verificar la equidad", note: "Participar implica riesgo y no garantiza beneficios." },
    trust: ["Polygon Mainnet", "Chainlink VRF v2.5", "Contrato verificado", "10 boletos ganadores", "Cobro directo", "Sin token del proyecto"],
    how: { eyebrow: "De la cartera al premio", title: "Cómo funciona Seren Lottery Chain", intro: "La interfaz explica cada paso y el contrato sigue siendo la fuente de precio, estado y resultados.", steps: [{ title: "Conecta en Polygon", body: "Elige una cartera del navegador o WalletConnect y cambia a Polygon Mainnet." }, { title: "Elige 1–100 boletos", body: "Define cantidad, créditos y un referente en la primera compra." }, { title: "Aprueba la cotización", body: "La aplicación simula el contrato y muestra el pago exacto antes de confirmar." }, { title: "Verifica y cobra", body: "Chainlink VRF aporta aleatoriedad y cada ganador cobra desde su propia cartera." }] },
    prizes: { eyebrow: "Diez posiciones premiadas", title: "Más oportunidades para un boleto", body: "Cada ronda finalizada selecciona diez IDs de boleto únicos y registra ganador, premio y estado de cobro.", first: "El 1.º puesto recibe la mayor parte calculada por el contrato", others: "Los puestos 2–10 comparten la asignación restante", note: "Los importes exactos proceden de los resultados on-chain; el fondo objetivo es informativo." },
    referral: { eyebrow: "Programa de referidos", title: "Invita participantes y consigue créditos", body: "El referente se fija en la primera compra. Los créditos administrados por el contrato pueden reducir el precio de boletos elegibles.", points: ["El referente debe haber participado", "No se permite autorreferencia", "Un crédito compra un boleto a mitad de precio", "El contrato valida cada crédito"] },
    account: { eyebrow: "Área personal", title: "Boletos, créditos y premios juntos", body: "Tras conectar, el panel lee los valores de tu dirección mediante la cartera elegida.", points: ["Saldo POL y boletos de la ronda", "Créditos y referente fijo", "Historial de rondas ganadoras", "Cobro individual y por lotes"] },
    transparency: { eyebrow: "Pruebas on-chain", title: "Revisa reglas, azar y resultados", body: "Consulta contrato verificado, transacciones Polygon, coordinador Chainlink VRF y ciclo de cada ronda.", points: ["Código verificado en PolygonScan", "Sin precios ni ganadores inventados", "Simulación antes de comprar", "Eventos públicos desde el despliegue"], contract: "Abrir contrato verificado" },
    faq: { eyebrow: "Antes de conectar", title: "Preguntas frecuentes", intro: "Conoce la mecánica y el riesgo.", items: [
      { question: "¿Qué es Seren Lottery Chain?", answer: "Una lotería por contrato en Polygon con compras, resultados y cobros verificables on-chain." }, { question: "¿Qué red necesito?", answer: "Polygon Mainnet, chain ID 137." }, { question: "¿Quién fija el precio?", answer: "El contrato verificado devuelve el precio y la cotización exacta." }, { question: "¿Cuántos boletos puedo comprar?", answer: "Entre 1 y 100 por compra confirmada." }, { question: "¿El fondo objetivo inicia el sorteo?", answer: "No; es informativo y el administrador autorizado inicia el proceso." }, { question: "¿Cómo se genera el azar?", answer: "Mediante una solicitud verificable a Chainlink VRF v2.5." }, { question: "¿Cuántos ganadores hay?", answer: "Diez IDs de boleto únicos por ronda finalizada." }, { question: "¿Puede ganar una cartera varias veces?", answer: "Sí, si posee varios boletos seleccionados." }, { question: "¿Los premios llegan automáticamente?", answer: "No; el ganador debe reclamarlos desde la cartera propietaria." }, { question: "¿Cómo funcionan los referidos?", answer: "Un participante previo se registra en la primera compra y el contrato gestiona créditos elegibles." }, { question: "¿Puedo cambiar de referente?", answer: "No después de la primera compra." }, { question: "¿Qué pasa si uso otra red?", answer: "Las acciones quedan bloqueadas hasta cambiar a Polygon Mainnet." }, { question: "¿Es una inversión?", answer: "No; puedes perder el POL utilizado y no existe beneficio garantizado." },
    ] },
    final: { title: "¿Listo para revisar la ronda?", body: "Conecta solo tras comprender reglas y riesgo. Los datos en vivo llegarán del contrato verificado.", primary: "Ir a la lotería", secondary: "Leer el contrato" },
    footer: { tagline: "Lotería on-chain transparente en Polygon", navigation: "Navegación", resources: "Verificación", contract: "Contrato inteligente", risk: "El fondo objetivo es informativo, se aplican comisiones y participar no garantiza beneficios.", rights: "© 2026 Seren Lottery Chain" },
  },
  zh: {
    metadata: { title: "Polygon 上透明的链上彩票", description: "Seren Lottery Chain 提供合约实时报价、Chainlink VRF v2.5 随机数、十个中奖票号和自主领奖。" },
    nav: { home: "首页", lottery: "彩票", how: "运作方式", winners: "中奖者", transparency: "透明度", faq: "常见问题" }, language: "语言",
    hero: { eyebrow: "POLYGON 上透明的链上开奖", title: "让幸运成为公开可验证的区块链事件", description: "十个中奖票号，Chainlink VRF v2.5 可验证随机数，每个阶段和结果均可独立核验。", primary: "参与本轮", secondary: "验证公平性", note: "参与存在风险，不保证收益。" },
    trust: ["Polygon 主网", "Chainlink VRF v2.5", "已验证合约", "10 个中奖票号", "直接领奖", "无项目代币"],
    how: { eyebrow: "从钱包到领奖", title: "Seren Lottery Chain 如何运作", intro: "界面解释每一步，合约始终是价格、轮次状态和结果的唯一事实来源。", steps: [{ title: "连接 Polygon", body: "选择浏览器钱包或 WalletConnect，并切换到 Polygon 主网。" }, { title: "选择 1–100 张票", body: "设置数量、推荐积分，并可在首次购买时填写推荐人。" }, { title: "确认准确报价", body: "应用先模拟合约调用，再由钱包确认当前付款金额。" }, { title: "验证并领奖", body: "Chainlink VRF 提供随机数，中奖者从自己的钱包领取奖金。" }] },
    prizes: { eyebrow: "十个中奖名次", title: "让每张票拥有更多机会", body: "每个完成轮次选择十个唯一票号，合约记录中奖者、票号、准确奖金和领奖状态。", first: "第 1 名获得合约计算的最大份额", others: "第 2–10 名分享其余奖金分配", note: "准确金额来自链上最终结果；目标奖池仅供参考，不会自动触发开奖。" },
    referral: { eyebrow: "推荐计划", title: "邀请参与者，获得未来积分", body: "推荐人只能在首次购买时设置并永久固定。合约发放的积分可降低符合条件票的价格。", points: ["推荐人必须参与过", "禁止自我推荐", "一个积分可半价购买一张票", "所有积分由合约验证"] },
    account: { eyebrow: "个人区域", title: "票、积分与领奖集中管理", body: "连接后，面板通过所选钱包直接读取地址数据。", points: ["POL 余额和本轮票数", "推荐积分与固定推荐人", "中奖轮次历史", "单笔与批量领奖"] },
    transparency: { eyebrow: "链上证据", title: "检查规则、随机数和结果", body: "可查看已验证合约、Polygon 交易、Chainlink VRF 协调器和每轮生命周期。", points: ["PolygonScan 已验证源码", "不虚构价格、奖池或中奖者", "购买前进行准确模拟", "从部署区块开始的公开事件"], contract: "打开已验证合约" },
    faq: { eyebrow: "连接前须知", title: "常见问题", intro: "先了解机制和风险。", items: [
      { question: "Seren Lottery Chain 是什么？", answer: "它是 Polygon 上的智能合约彩票，购买、开奖结果和领奖均可在链上验证。" }, { question: "需要哪个网络？", answer: "Polygon 主网，chain ID 137。" }, { question: "票价如何确定？", answer: "由已验证合约返回当前价格和准确报价。" }, { question: "一次可以买多少张？", answer: "每笔已确认购买可买 1 到 100 张。" }, { question: "达到目标奖池会自动开奖吗？", answer: "不会；目标仅供参考，由授权管理员启动合约流程。" }, { question: "随机数如何生成？", answer: "合约使用 Chainlink VRF v2.5 的可验证随机数。" }, { question: "有多少中奖者？", answer: "每个完成轮次选择十个唯一票号。" }, { question: "同一钱包能多次中奖吗？", answer: "可以，只要持有多个被选中的票号。" }, { question: "奖金会自动发送吗？", answer: "不会，中奖钱包必须主动领取。" }, { question: "推荐计划如何运作？", answer: "首次购买可登记一位既有参与者，合约按规则管理积分。" }, { question: "能更改推荐人吗？", answer: "首次购买登记后不能更改。" }, { question: "钱包网络错误怎么办？", answer: "切换到 Polygon 主网后才能使用实时操作。" }, { question: "这是投资吗？", answer: "不是；投入的 POL 可能损失，不保证任何利润。" },
    ] },
    final: { title: "准备查看当前轮次？", body: "理解规则和风险后再连接。实时数据将通过钱包来自已验证 Polygon 合约。", primary: "进入彩票", secondary: "阅读合约" },
    footer: { tagline: "Polygon 上透明的链上彩票", navigation: "导航", resources: "验证", contract: "智能合约", risk: "目标奖池仅供参考，票务收入会收取费用，参与不保证收益。", rights: "© 2026 Seren Lottery Chain" },
  },
  hi: {
    metadata: { title: "Polygon पर पारदर्शी ऑन-चेन लॉटरी", description: "Seren Lottery Chain में कॉन्ट्रैक्ट मूल्य, Chainlink VRF v2.5, दस विजेता टिकट और स्वयं पुरस्कार दावा शामिल हैं।" },
    nav: { home: "होम", lottery: "लॉटरी", how: "कैसे काम करता है", winners: "विजेता", transparency: "पारदर्शिता", faq: "सवाल" }, language: "भाषा",
    hero: { eyebrow: "POLYGON पर पारदर्शी ON-CHAIN DRAW", title: "भाग्य एक blockchain event बनता है", description: "दस winning tickets, Chainlink VRF v2.5 की verifiable randomness और हर चरण स्वतंत्र रूप से जाँचने योग्य।", primary: "राउंड में भाग लें", secondary: "निष्पक्षता जाँचें", note: "भागीदारी में जोखिम है; लाभ की गारंटी नहीं।" },
    trust: ["Polygon Mainnet", "Chainlink VRF v2.5", "सत्यापित कॉन्ट्रैक्ट", "10 विजेता टिकट", "सीधा claim", "कोई project token नहीं"],
    how: { eyebrow: "वॉलेट से पुरस्कार तक", title: "Seren Lottery Chain कैसे काम करता है", intro: "इंटरफ़ेस हर चरण समझाता है और मूल्य, स्थिति व परिणाम का स्रोत कॉन्ट्रैक्ट रहता है।", steps: [{ title: "Polygon से जुड़ें", body: "ब्राउज़र वॉलेट या WalletConnect चुनें और Polygon Mainnet पर जाएँ।" }, { title: "1–100 टिकट चुनें", body: "मात्रा, referral credits और पहली खरीद पर referrer चुनें।" }, { title: "सटीक कोट मंज़ूर करें", body: "ऐप कॉन्ट्रैक्ट कॉल को simulate करके वॉलेट में सही भुगतान दिखाता है।" }, { title: "सत्यापित करें और दावा करें", body: "Chainlink VRF randomness देता है और विजेता अपने वॉलेट से पुरस्कार दावा करते हैं।" }] },
    prizes: { eyebrow: "दस पुरस्कार स्थान", title: "हर टिकट के लिए अधिक अवसर", body: "पूर्ण राउंड में दस अलग ticket ID चुने जाते हैं और विजेता, पुरस्कार व claim स्थिति कॉन्ट्रैक्ट में दर्ज होती है।", first: "पहले स्थान को कॉन्ट्रैक्ट द्वारा गणना की सबसे बड़ी हिस्सेदारी", others: "स्थान 2–10 शेष पुरस्कार बाँटते हैं", note: "सटीक भुगतान अंतिम ऑन-चेन परिणाम से आता है; target pool केवल सूचना है।" },
    referral: { eyebrow: "रेफरल कार्यक्रम", title: "प्रतिभागी आमंत्रित करें, credits पाएँ", body: "Referrer केवल पहली खरीद पर तय होता है। कॉन्ट्रैक्ट credits पात्र टिकट की कीमत घटा सकते हैं।", points: ["Referrer पहले भाग ले चुका हो", "Self-referral मान्य नहीं", "एक credit से एक टिकट आधी कीमत पर", "हर credit कॉन्ट्रैक्ट जाँचता है"] },
    account: { eyebrow: "व्यक्तिगत क्षेत्र", title: "टिकट, credits और claims एक जगह", body: "जुड़ने के बाद dashboard चुने वॉलेट से आपके पते का डेटा पढ़ता है।", points: ["POL balance और मौजूदा टिकट", "Referral credits और तय referrer", "जीते हुए राउंड का इतिहास", "एकल और batch prize claim"] },
    transparency: { eyebrow: "ऑन-चेन प्रमाण", title: "नियम, randomness और परिणाम जाँचें", body: "सत्यापित कॉन्ट्रैक्ट, Polygon transactions, Chainlink VRF और हर राउंड का lifecycle देखें।", points: ["PolygonScan पर सत्यापित code", "कोई नकली मूल्य या विजेता नहीं", "खरीद से पहले simulation", "Deployment block से सार्वजनिक events"], contract: "सत्यापित कॉन्ट्रैक्ट खोलें" },
    faq: { eyebrow: "जुड़ने से पहले", title: "अक्सर पूछे सवाल", intro: "पहले प्रक्रिया और जोखिम समझें।", items: [
      { question: "Seren Lottery Chain क्या है?", answer: "Polygon का smart-contract lottery जहाँ खरीद, नतीजे और claims ऑन-चेन सत्यापित हैं।" }, { question: "कौन सा network चाहिए?", answer: "Polygon Mainnet, chain ID 137।" }, { question: "Ticket price कहाँ से आता है?", answer: "सत्यापित कॉन्ट्रैक्ट मौजूदा price और exact quote देता है।" }, { question: "कितने टिकट खरीद सकता हूँ?", answer: "एक confirmed खरीद में 1 से 100।" }, { question: "Target pool से draw शुरू होता है?", answer: "नहीं; यह सूचना है और authorized admin प्रक्रिया शुरू करता है।" }, { question: "Randomness कैसे मिलता है?", answer: "Chainlink VRF v2.5 से सत्यापन योग्य randomness मिलता है।" }, { question: "कितने विजेता हैं?", answer: "हर finalized round में दस अलग ticket ID।" }, { question: "एक wallet कई बार जीत सकता है?", answer: "हाँ, यदि उसके कई टिकट चुने जाएँ।" }, { question: "पुरस्कार अपने आप आता है?", answer: "नहीं; विजेता wallet को claim करना होता है।" }, { question: "Referral कैसे काम करता है?", answer: "पहली खरीद पर पुराने participant को दर्ज कर contract credits चला सकता है।" }, { question: "Referrer बदल सकता हूँ?", answer: "पहली खरीद के बाद नहीं।" }, { question: "गलत network पर क्या होगा?", answer: "Polygon Mainnet पर जाने तक live actions बंद रहते हैं।" }, { question: "क्या यह investment है?", answer: "नहीं; खर्च POL खो सकता है और profit की गारंटी नहीं।" },
    ] },
    final: { title: "मौजूदा राउंड देखने के लिए तैयार?", body: "नियम और जोखिम समझकर ही जुड़ें। Live values सत्यापित Polygon कॉन्ट्रैक्ट से आएँगी।", primary: "लॉटरी पर जाएँ", secondary: "कॉन्ट्रैक्ट पढ़ें" },
    footer: { tagline: "Polygon पर पारदर्शी ऑन-चेन लॉटरी", navigation: "नेविगेशन", resources: "सत्यापन", contract: "स्मार्ट कॉन्ट्रैक्ट", risk: "Target pool सूचना है, ticket revenue पर fee लागू है और लाभ की गारंटी नहीं।", rights: "© 2026 Seren Lottery Chain" },
  },
  ar: {
    metadata: { title: "يانصيب شفاف على شبكة Polygon", description: "Seren Lottery Chain يقدم سعراً من العقد وعشوائية Chainlink VRF v2.5 وعشرة تذاكر فائزة ومطالبة ذاتية بالجوائز." },
    nav: { home: "الرئيسية", lottery: "اليانصيب", how: "كيف يعمل", winners: "الفائزون", transparency: "الشفافية", faq: "الأسئلة" }, language: "اللغة",
    hero: { eyebrow: "سحب شفاف على السلسلة في POLYGON", title: "يصبح الحظ حدثاً على البلوكشين", description: "عشر تذاكر فائزة وعشوائية Chainlink VRF v2.5 قابلة للتحقق، وكل مرحلة ونتيجة قابلة للفحص.", primary: "شارك في الجولة", secondary: "تحقق من النزاهة", note: "المشاركة تنطوي على مخاطر ولا تضمن الربح." },
    trust: ["Polygon Mainnet", "Chainlink VRF v2.5", "عقد موثق", "10 تذاكر فائزة", "مطالبة مباشرة", "لا يوجد رمز للمشروع"],
    how: { eyebrow: "من المحفظة إلى الجائزة", title: "كيف يعمل Seren Lottery Chain", intro: "تشرح الواجهة كل خطوة ويبقى العقد مصدر الحقيقة للسعر وحالة الجولة والنتائج.", steps: [{ title: "اتصل بشبكة Polygon", body: "اختر محفظة المتصفح أو WalletConnect وانتقل إلى Polygon Mainnet." }, { title: "اختر 1–100 تذكرة", body: "حدد الكمية ورصيد الإحالة والمُحيل في أول عملية شراء." }, { title: "وافق على السعر الدقيق", body: "يحاكي التطبيق استدعاء العقد ويعرض المبلغ الحالي قبل تأكيد المحفظة." }, { title: "تحقق وطالب", body: "توفر Chainlink VRF العشوائية ويطالب الفائز بجائزته من محفظته." }] },
    prizes: { eyebrow: "عشرة مراكز فائزة", title: "فرص أكثر لكل تذكرة", body: "تختار كل جولة مكتملة عشرة أرقام تذاكر فريدة ويسجل العقد الفائز والجائزة وحالة المطالبة.", first: "يحصل المركز الأول على أكبر حصة يحسبها العقد", others: "تتقاسم المراكز 2–10 بقية توزيع الجوائز", note: "المبالغ الدقيقة تأتي من النتائج النهائية على السلسلة؛ المجمع المستهدف معلومة فقط." },
    referral: { eyebrow: "برنامج الإحالة", title: "ادعُ المشاركين واكسب رصيداً", body: "يُحدد المُحيل في أول شراء فقط ويبقى ثابتاً. يمكن لرصيد العقد خفض سعر التذاكر المؤهلة.", points: ["يجب أن يكون المُحيل مشاركاً سابقاً", "الإحالة الذاتية مرفوضة", "الرصيد الواحد يشتري تذكرة بنصف السعر", "العقد يتحقق من كل رصيد"] },
    account: { eyebrow: "المساحة الشخصية", title: "التذاكر والأرصدة والجوائز في مكان واحد", body: "بعد الاتصال تقرأ لوحة المعلومات قيم عنوانك عبر مزود المحفظة المختار.", points: ["رصيد POL وتذاكر الجولة", "رصيد الإحالة والمُحيل الثابت", "سجل الجولات الفائزة", "مطالبة فردية ومجمعة"] },
    transparency: { eyebrow: "دليل على السلسلة", title: "افحص القواعد والعشوائية والنتائج", body: "يعرض Seren العقد الموثق ومعاملات Polygon ومنسق Chainlink VRF ودورة كل جولة.", points: ["شفرة موثقة على PolygonScan", "لا أسعار أو فائزين مختلقين", "محاكاة دقيقة قبل الشراء", "أحداث عامة منذ كتلة النشر"], contract: "افتح العقد الموثق" },
    faq: { eyebrow: "قبل الاتصال", title: "الأسئلة الشائعة", intro: "افهم الآلية والمخاطر أولاً.", items: [
      { question: "ما هو Seren Lottery Chain؟", answer: "يانصيب بعقد ذكي على Polygon يمكن التحقق من مشترياته ونتائجه ومطالباته على السلسلة." }, { question: "ما الشبكة المطلوبة؟", answer: "Polygon Mainnet، رقم السلسلة 137." }, { question: "كيف يُحدد سعر التذكرة؟", answer: "يعيد العقد الموثق السعر الحالي وعرض الشراء الدقيق." }, { question: "كم تذكرة يمكنني شراءها؟", answer: "من 1 إلى 100 في عملية شراء مؤكدة واحدة." }, { question: "هل يبدأ السحب عند بلوغ المجمع المستهدف؟", answer: "لا؛ هو معلومة ويبدأ المسؤول المخول إجراء العقد." }, { question: "كيف تُولد العشوائية؟", answer: "باستخدام عشوائية قابلة للتحقق من Chainlink VRF v2.5." }, { question: "كم عدد الفائزين؟", answer: "عشرة أرقام تذاكر فريدة في كل جولة نهائية." }, { question: "هل يمكن لمحفظة أن تفوز أكثر من مرة؟", answer: "نعم إذا امتلكت عدة تذاكر مختارة." }, { question: "هل تُرسل الجوائز تلقائياً؟", answer: "لا؛ يجب على المحفظة الفائزة المطالبة بالجائزة." }, { question: "كيف تعمل الإحالة؟", answer: "يُسجل مشارك سابق في أول شراء ويدير العقد الأرصدة المؤهلة." }, { question: "هل يمكن تغيير المُحيل؟", answer: "لا بعد تسجيل أول عملية شراء." }, { question: "ماذا يحدث على شبكة خاطئة؟", answer: "تبقى الإجراءات معطلة حتى الانتقال إلى Polygon Mainnet." }, { question: "هل هذه استثمار؟", answer: "لا؛ قد تفقد POL المستخدمة ولا يوجد ربح مضمون." },
    ] },
    final: { title: "هل أنت مستعد لفحص الجولة الحالية؟", body: "اتصل فقط بعد فهم القواعد والمخاطر. تأتي القيم الحية من عقد Polygon الموثق عبر محفظتك.", primary: "انتقل إلى اليانصيب", secondary: "اقرأ العقد" },
    footer: { tagline: "يانصيب شفاف على شبكة Polygon", navigation: "التنقل", resources: "التحقق", contract: "العقد الذكي", risk: "المجمع المستهدف معلومة وتطبق رسوم على إيراد التذاكر ولا تضمن المشاركة الربح.", rights: "© 2026 Seren Lottery Chain" },
  },
  fr: {
    metadata: { title: "Loterie on-chain transparente sur Polygon", description: "Seren Lottery Chain associe devis du contrat, Chainlink VRF v2.5, dix tickets gagnants et réclamation autonome des prix." },
    nav: { home: "Accueil", lottery: "Loterie", how: "Fonctionnement", winners: "Gagnants", transparency: "Transparence", faq: "Questions" }, language: "Langue",
    hero: { eyebrow: "TIRAGE ON-CHAIN TRANSPARENT SUR POLYGON", title: "La fortune devient un événement blockchain", description: "Dix tickets gagnants, un aléa Chainlink VRF v2.5 vérifiable et chaque étape contrôlable.", primary: "Participer au round", secondary: "Vérifier l’équité", note: "La participation comporte un risque et ne garantit aucun bénéfice." },
    trust: ["Polygon Mainnet", "Chainlink VRF v2.5", "Contrat vérifié", "10 tickets gagnants", "Réclamation directe", "Aucun token de projet"],
    how: { eyebrow: "Du wallet au prix", title: "Comment fonctionne Seren Lottery Chain", intro: "L’interface explique chaque étape et le contrat reste la source du prix, du statut et des résultats.", steps: [{ title: "Connectez-vous à Polygon", body: "Choisissez un wallet navigateur ou WalletConnect et passez sur Polygon Mainnet." }, { title: "Choisissez 1–100 tickets", body: "Définissez quantité, crédits et parrain lors du premier achat." }, { title: "Validez le devis exact", body: "L’application simule l’appel et affiche le paiement actuel avant confirmation." }, { title: "Vérifiez et réclamez", body: "Chainlink VRF fournit l’aléa et le gagnant réclame depuis son wallet." }] },
    prizes: { eyebrow: "Dix places gagnantes", title: "Davantage de chances pour chaque ticket", body: "Chaque round finalisé sélectionne dix IDs uniques et enregistre gagnant, prix et statut de réclamation.", first: "La 1re place reçoit la plus grande part calculée par le contrat", others: "Les places 2–10 partagent l’allocation restante", note: "Les montants exacts viennent des résultats on-chain ; la cagnotte cible est informative." },
    referral: { eyebrow: "Programme de parrainage", title: "Invitez des participants et gagnez des crédits", body: "Le parrain est fixé au premier achat. Les crédits gérés par le contrat peuvent réduire le prix de tickets éligibles.", points: ["Le parrain doit avoir participé", "L’auto-parrainage est refusé", "Un crédit achète un ticket à moitié prix", "Le contrat valide chaque crédit"] },
    account: { eyebrow: "Espace personnel", title: "Tickets, crédits et prix réunis", body: "Après connexion, le tableau de bord lit les données de votre adresse via le wallet choisi.", points: ["Solde POL et tickets du round", "Crédits et parrain fixe", "Historique des rounds gagnants", "Réclamations unitaires et groupées"] },
    transparency: { eyebrow: "Preuves on-chain", title: "Contrôlez règles, aléa et résultats", body: "Consultez contrat vérifié, transactions Polygon, coordinateur Chainlink VRF et cycle des rounds.", points: ["Code vérifié sur PolygonScan", "Aucun prix ni gagnant inventé", "Simulation avant achat", "Événements publics depuis le déploiement"], contract: "Ouvrir le contrat vérifié" },
    faq: { eyebrow: "Avant la connexion", title: "Questions fréquentes", intro: "Comprenez le fonctionnement et le risque.", items: [
      { question: "Qu’est-ce que Seren Lottery Chain ?", answer: "Une loterie par smart contract sur Polygon dont achats, résultats et réclamations sont vérifiables on-chain." }, { question: "Quel réseau faut-il ?", answer: "Polygon Mainnet, chain ID 137." }, { question: "Qui fixe le prix ?", answer: "Le contrat vérifié renvoie le prix et le devis exact." }, { question: "Combien de tickets puis-je acheter ?", answer: "Entre 1 et 100 par achat confirmé." }, { question: "La cagnotte cible déclenche-t-elle le tirage ?", answer: "Non ; elle est informative et un administrateur autorisé démarre le processus." }, { question: "Comment l’aléa est-il produit ?", answer: "Avec l’aléa vérifiable de Chainlink VRF v2.5." }, { question: "Combien y a-t-il de gagnants ?", answer: "Dix IDs de tickets uniques par round finalisé." }, { question: "Un wallet peut-il gagner plusieurs fois ?", answer: "Oui s’il possède plusieurs tickets sélectionnés." }, { question: "Les prix sont-ils envoyés automatiquement ?", answer: "Non ; le wallet gagnant doit les réclamer." }, { question: "Comment marche le parrainage ?", answer: "Un ancien participant est enregistré au premier achat et le contrat gère les crédits." }, { question: "Puis-je changer de parrain ?", answer: "Non après le premier achat." }, { question: "Que faire sur le mauvais réseau ?", answer: "Passez sur Polygon Mainnet pour activer les actions." }, { question: "Est-ce un investissement ?", answer: "Non ; le POL engagé peut être perdu et aucun profit n’est garanti." },
    ] },
    final: { title: "Prêt à examiner le round actuel ?", body: "Connectez-vous seulement après avoir compris règles et risques. Les données viendront du contrat Polygon vérifié.", primary: "Aller à la loterie", secondary: "Lire le contrat" },
    footer: { tagline: "Loterie on-chain transparente sur Polygon", navigation: "Navigation", resources: "Vérification", contract: "Smart contract", risk: "La cagnotte cible est informative, des frais s’appliquent et participer ne garantit aucun bénéfice.", rights: "© 2026 Seren Lottery Chain" },
  },
  pt: {
    metadata: { title: "Loteria on-chain transparente na Polygon", description: "Seren Lottery Chain oferece cotação do contrato, Chainlink VRF v2.5, dez bilhetes vencedores e resgate autônomo." },
    nav: { home: "Início", lottery: "Loteria", how: "Como funciona", winners: "Vencedores", transparency: "Transparência", faq: "Perguntas" }, language: "Idioma",
    hero: { eyebrow: "SORTEIO ON-CHAIN TRANSPARENTE NA POLYGON", title: "A sorte se torna um evento blockchain", description: "Dez bilhetes vencedores, aleatoriedade verificável da Chainlink VRF v2.5 e cada etapa comprovável.", primary: "Participar da rodada", secondary: "Verificar a equidade", note: "Participar envolve risco e não garante lucro." },
    trust: ["Polygon Mainnet", "Chainlink VRF v2.5", "Contrato verificado", "10 bilhetes vencedores", "Resgate direto", "Sem token do projeto"],
    how: { eyebrow: "Da carteira ao prêmio", title: "Como funciona a Seren Lottery Chain", intro: "A interface explica cada etapa e o contrato continua sendo a fonte de preço, status e resultados.", steps: [{ title: "Conecte na Polygon", body: "Escolha carteira do navegador ou WalletConnect e mude para Polygon Mainnet." }, { title: "Escolha 1–100 bilhetes", body: "Defina quantidade, créditos e indicador na primeira compra." }, { title: "Aprove a cotação exata", body: "O app simula o contrato e mostra o pagamento atual antes da confirmação." }, { title: "Verifique e resgate", body: "Chainlink VRF fornece aleatoriedade e o vencedor resgata na própria carteira." }] },
    prizes: { eyebrow: "Dez posições premiadas", title: "Mais oportunidades para cada bilhete", body: "Cada rodada finalizada seleciona dez IDs únicos e registra vencedor, prêmio e status de resgate.", first: "O 1º lugar recebe a maior parcela calculada pelo contrato", others: "Os lugares 2–10 dividem a alocação restante", note: "Valores exatos vêm dos resultados on-chain; o fundo-alvo é informativo." },
    referral: { eyebrow: "Programa de indicação", title: "Convide participantes e ganhe créditos", body: "O indicador é fixado na primeira compra. Créditos geridos pelo contrato podem reduzir o preço de bilhetes elegíveis.", points: ["O indicador deve ter participado", "Autoindicação é recusada", "Um crédito compra um bilhete pela metade", "O contrato valida cada crédito"] },
    account: { eyebrow: "Área pessoal", title: "Bilhetes, créditos e prêmios juntos", body: "Após conectar, o painel lê os valores do seu endereço pela carteira escolhida.", points: ["Saldo POL e bilhetes da rodada", "Créditos e indicador fixo", "Histórico de rodadas vencedoras", "Resgate individual e em lote"] },
    transparency: { eyebrow: "Provas on-chain", title: "Confira regras, aleatoriedade e resultados", body: "Veja contrato verificado, transações Polygon, coordenador Chainlink VRF e ciclo das rodadas.", points: ["Código verificado no PolygonScan", "Sem preços ou vencedores inventados", "Simulação antes da compra", "Eventos públicos desde o deploy"], contract: "Abrir contrato verificado" },
    faq: { eyebrow: "Antes de conectar", title: "Perguntas frequentes", intro: "Entenda o funcionamento e o risco.", items: [
      { question: "O que é Seren Lottery Chain?", answer: "Uma loteria por smart contract na Polygon com compras, resultados e resgates verificáveis on-chain." }, { question: "Qual rede preciso usar?", answer: "Polygon Mainnet, chain ID 137." }, { question: "Quem define o preço?", answer: "O contrato verificado retorna preço e cotação exata." }, { question: "Quantos bilhetes posso comprar?", answer: "De 1 a 100 por compra confirmada." }, { question: "O fundo-alvo inicia o sorteio?", answer: "Não; ele é informativo e um administrador autorizado inicia o processo." }, { question: "Como nasce a aleatoriedade?", answer: "Com aleatoriedade verificável da Chainlink VRF v2.5." }, { question: "Quantos vencedores existem?", answer: "Dez IDs de bilhete únicos em cada rodada finalizada." }, { question: "Uma carteira pode vencer mais de uma vez?", answer: "Sim, se possuir vários bilhetes selecionados." }, { question: "Os prêmios chegam automaticamente?", answer: "Não; a carteira vencedora precisa resgatar." }, { question: "Como funciona a indicação?", answer: "Um participante anterior é registrado na primeira compra e o contrato gerencia créditos." }, { question: "Posso mudar o indicador?", answer: "Não depois da primeira compra." }, { question: "E se eu estiver na rede errada?", answer: "As ações ficam bloqueadas até mudar para Polygon Mainnet." }, { question: "Isso é investimento?", answer: "Não; o POL usado pode ser perdido e não há lucro garantido." },
    ] },
    final: { title: "Pronto para conferir a rodada atual?", body: "Conecte apenas após entender regras e riscos. Os dados virão do contrato Polygon verificado.", primary: "Ir para a loteria", secondary: "Ler o contrato" },
    footer: { tagline: "Loteria on-chain transparente na Polygon", navigation: "Navegação", resources: "Verificação", contract: "Contrato inteligente", risk: "O fundo-alvo é informativo, taxas se aplicam e participar não garante lucro.", rights: "© 2026 Seren Lottery Chain" },
  },
};
